export const S = {
  navDomov: 'Domov',
  navPonuky: 'Ponuky',
  navPridat: 'Pridať',
  navPridatPonuku: 'Pridať ponuku',
  navSpravy: 'Správy',
  navProfil: 'Profil',
  searchHint: 'Vyhľadávanie',
  noJobsYet: 'Zatiaľ žiadne pracovné ponuky.',
  mojePonuky: 'Moje ponuky',
  aktivnePonuky: 'Aktívne ponuky',
  noApplicationsYet: 'Zatiaľ nemáte žiadne prihlásenia na ponuky.',
  myOffersPlaceholder: 'Tu sa zobrazia vaše vytvorené ponuky.',
  pleaseSignIn: 'Prihláste sa.',
  login: 'Prihlásenie',
  createAccount: 'Vytvoriť účet',
  register: 'Registrácia',
  email: 'Email',
  password: 'Heslo',
  signIn: 'Prihlásiť sa',
  signUp: 'Registrovať sa',
  noAccount: 'Nemáte účet?',
  haveAccount: 'Už máte účet?',
  roleLabel: 'Typ účtu',
  roleCompany: 'Firma',
  roleIndividual: 'Jednotlivec',
  stepAccountType: 'Typ účtu',
  stepCredentials: 'Registrácia',
  stepRoles: 'Čo vás zaujíma',
  stepCompleteProfile: 'Dokončenie profilu',
  stepPreferences: 'Preferencie',
  preferencesOptional: 'Tento krok je voliteľný – môžete preskočiť.',
  category: 'Kategória',
  preferredLocation: 'Preferovaná lokácia',
  workLocation: 'Lokalita práce',
  skipForNow: 'Preskočiť zatiaľ',
  continue: 'Pokračovať',
  welcomeTitle: 'Účet vytvorený',
  welcomeGreeting: 'Vitajte',
  enterTheApp: 'Vstúpiť do aplikácie',
  confirmEmailTitle: 'Vitajte v aplikácii',
  confirmEmailMessage:
    'Účet bol vytvorený. Potvrďte registráciu cez odkaz v e-maili a potom sa prihláste. Po prihlásení vstúpite do aplikácie.',
  stepIntoApp: 'Vstúpiť do aplikácie',
  alreadyConfirmedSignIn: 'Už potvrdene? Prihlásiť sa',
  preferencesLookingTitle: 'Preferencie – hľadám prácu',
  preferencesOfferingTitle: 'Preferencie – ponúkam prácu',
  lookingForWork: 'Hľadám prácu',
  offeringWork: 'Ponúkam prácu',
  bothRoles: 'Oboje',
  termsAgree: 'Súhlasím s podmienkami používania',
  termsRequired: 'Pre registráciu je potrebný súhlas s podmienkami.',
  experience: 'Skúsenosti',
  registrationNumber: 'IČO / registračné číslo',
  website: 'Web',
  logoUrl: 'Logo (URL)',
  preferredJobType: 'O aký druh práce máte záujem',
  profilTitle: 'Profil',
  logout: 'Odhlásiť sa',
  fullName: 'Celé meno',
  firstName: 'Meno',
  lastName: 'Priezvisko',
  companyName: 'Názov firmy',
  registeredOffice: 'Sídlo firmy / adresa',
  companyIdIco: 'IČO',
  taxIdDic: 'DIČ',
  vatPayer: 'Som platca DPH',
  vatIdIcDph: 'IČ DPH',
  bio: 'Bio',
  education: 'Vzdelanie',
  skills: 'Zručnosti',
  jobInterests: 'O aký druh práce máte záujem',
  location: 'Lokácia',
  description: 'Popis',
  sector: 'Sektor / oblasť',
  emailReadOnly: 'Email (iba na zobrazenie)',
  planyTitle: 'Plány',
  myPlan: 'Môj plán',
  selectPlan: 'Vybrať',
  noSubscription: 'Nemáte aktívne predplatné.',
  jobOffers: 'Pracovné ponuky',
  postJob: 'Pridať ponuku',
  apply: 'Prihlásiť sa na ponuku',
  noJobOffersYet: 'Zatiaľ žiadne ponuky.',
  statusDraft: 'Koncept',
  statusActive: 'Aktívna',
  statusInactive: 'Neaktívna',
  jobTitle: 'Názov',
  jobDescription: 'Popis',
  jobRequirements: 'Požiadavky',
  jobSalary: 'Plat',
  jobType: 'Druh práce',
  jobLocationOptional: 'Lokácia (voliteľné)',
  createAndPublish: 'Vytvoriť a zverejniť',
  saveDraft: 'Uložiť koncept',
  sortBy: 'Zoradiť podľa',
  sortNewest: 'Od najnovšieho',
  sortSalary: 'Najviac platiaceho',
  loading: 'Načítavam...',
  save: 'Uložiť',
  cancel: 'Zrušiť',
  required: 'Povinné pole',
  chat: 'Chat',
  noConversations: 'Zatiaľ nemáte žiadne konverzácie.',
  publishWithoutPayment: 'Zverejniť ponuku (bez platby)',
  jobNotFound: 'Ponuka nebola nájdená.',
  navHladat: 'Hľadať',
  navPlany: 'Plány',
  findWork: 'Nájsť prácu',
  findWorkCount: 'ponúk k dispozícii',
  categories: 'Kategórie',
  latestOffers: 'Najnovšie ponuky',
  all: 'Všetky',
  statsPonuky: 'Ponúk',
  statsPracantov: 'Pracantov',
  statsHodnotenie: 'Hodnotenie',
  searchWork: 'Nájsť prácu',
  searchWorkPlaceholder: 'Hľadať prácu...',
  clearFilters: 'Zrušiť filtre',
  urgentOnly: 'Len urgentné',
  minPerHour: 'Min. €/hod',
  filterCategory: 'Kategória',
  filterJobType: 'Typ úväzku',
  filterSort: 'Triediť',
  allCategories: 'Všetky kategórie',
  anyJobType: 'Akýkoľvek úväzok',
  sortNewestFirst: 'Najnovšie',
  sortOldestFirst: 'Najstaršie',
  sortHighestPay: 'Najvyššia odmena',
  recommendedForYou: 'Odporúčané pre vás',
  noOffers: 'Žiadne ponuky',
  noOffersTryFilters: 'Skúste zmeniť filtre alebo sa vráťte neskôr',
  newJobOffer: 'Nová ponuka práce',
  categoryRequired: 'Kategória *',
  selectCategory: 'Vyberte kategóriu',
  workersNeeded: 'Počet pracantov',
  compensationType: 'Typ odmeny',
  compensationAmount: 'Suma (€)',
  applicationDeadline: 'Dátum uzávierky prihlásení',
  completionDeadline: 'Termín dokončenia',
  locationAddress: 'Adresa / lokalita',
};
