export const S = {
  navDomov: 'Domov',
  navPonuky: 'Ponuky',
  navPridat: 'Pridať',
  navPridatPonuku: 'Pridať ponuku',
  navSpravy: 'Správy',
  navProfil: 'Profil',
  searchHint: 'Vyhľadávanie',
  noJobsYet: 'Zatiaľ žiadne pracovné ponuky.',
  mojePonuky: 'Moje ponuky',
  aktivnePonuky: 'Aktívne ponuky',
  noApplicationsYet: 'Zatiaľ nemáte žiadne prihlásenia na ponuky.',
  myOffersPlaceholder: 'Tu sa zobrazia vaše vytvorené ponuky.',
  pleaseSignIn: 'Prihláste sa.',
  login: 'Prihlásenie',
  register: 'Registrácia',
  email: 'Email',
  password: 'Heslo',
  signIn: 'Prihlásiť sa',
  signUp: 'Registrovať sa',
  noAccount: 'Nemáte účet?',
  haveAccount: 'Už máte účet?',
  roleLabel: 'Typ účtu',
  roleCompany: 'Firma / poskytovateľ práce',
  roleIndividual: 'Hľadám prácu (brigádnik)',
  profilTitle: 'Profil',
  logout: 'Odhlásiť sa',
  fullName: 'Celé meno',
  companyName: 'Názov firmy',
  bio: 'Bio',
  education: 'Vzdelanie',
  skills: 'Zručnosti',
  jobInterests: 'O aký druh práce máte záujem',
  location: 'Lokácia',
  description: 'Popis',
  sector: 'Sektor / oblasť',
  emailReadOnly: 'Email (iba na zobrazenie)',
  planyTitle: 'Plány',
  myPlan: 'Môj plán',
  selectPlan: 'Vybrať',
  noSubscription: 'Nemáte aktívne predplatné.',
  jobOffers: 'Pracovné ponuky',
  postJob: 'Pridať ponuku',
  apply: 'Prihlásiť sa na ponuku',
  noJobOffersYet: 'Zatiaľ žiadne ponuky.',
  statusDraft: 'Koncept',
  statusActive: 'Aktívna',
  statusInactive: 'Neaktívna',
  jobTitle: 'Názov',
  jobDescription: 'Popis',
  jobRequirements: 'Požiadavky',
  jobSalary: 'Plat',
  jobType: 'Druh práce',
  jobLocationOptional: 'Lokácia (voliteľné)',
  createAndPublish: 'Vytvoriť a zverejniť',
  saveDraft: 'Uložiť koncept',
  sortBy: 'Zoradiť podľa',
  sortNewest: 'Od najnovšieho',
  sortSalary: 'Najviac platiaceho',
  loading: 'Načítavam...',
  save: 'Uložiť',
  cancel: 'Zrušiť',
  required: 'Povinné pole',
  chat: 'Chat',
  noConversations: 'Zatiaľ nemáte žiadne konverzácie.',
  publishWithoutPayment: 'Zverejniť ponuku (bez platby)',
  jobNotFound: 'Ponuka nebola nájdená.',
  navHladat: 'Hľadať',
  navPlany: 'Plány',
  findWork: 'Nájsť prácu',
  findWorkCount: 'ponúk k dispozícii',
  categories: 'Kategórie',
  latestOffers: 'Najnovšie ponuky',
  all: 'Všetky',
  statsPonuky: 'Ponúk',
  statsPracantov: 'Pracantov',
  statsHodnotenie: 'Hodnotenie',
  searchWork: 'Nájsť prácu',
  searchWorkPlaceholder: 'Hľadať prácu...',
  clearFilters: 'Zrušiť filtre',
  urgentOnly: 'Len urgentné',
  minPerHour: 'Min. €/hod',
  filterCategory: 'Kategória',
  filterJobType: 'Typ úväzku',
  filterSort: 'Triediť',
  allCategories: 'Všetky kategórie',
  anyJobType: 'Akýkoľvek úväzok',
  sortNewestFirst: 'Najnovšie',
  sortOldestFirst: 'Najstaršie',
  sortHighestPay: 'Najvyššia odmena',
  recommendedForYou: 'Odporúčané pre vás',
  noOffers: 'Žiadne ponuky',
  noOffersTryFilters: 'Skúste zmeniť filtre alebo sa vráťte neskôr',
  newJobOffer: 'Nová ponuka práce',
  categoryRequired: 'Kategória *',
  selectCategory: 'Vyberte kategóriu',
  workersNeeded: 'Počet pracantov',
  compensationType: 'Typ odmeny',
  compensationAmount: 'Suma (€)',
  applicationDeadline: 'Dátum uzávierky prihlásení',
  completionDeadline: 'Termín dokončenia',
  locationAddress: 'Adresa / lokalita',
};
