/**
 * CV shell PATCH field names accepted by `CvService.patchCv` personal/shell/job maps.
 * Incremental TypeScript surface for the CV module (see plan: backend-ts-migrate).
 */
export const CV_HEADER_PATCH_FIELD_KEYS = [
  'display_title',
  'template_key',
  'visible_to_employers',
  'optional_sections',
  'first_name',
  'last_name',
  'gender',
  'show_academic_title',
  'title_before_name',
  'title_after_name',
  'birth_date',
  'show_birth_date',
  'email',
  'phone',
  'linkedin_url',
  'show_contact_details',
  'address_country',
  'address_city',
  'address_street',
  'address_postal_code',
  'address_district',
  'about_me',
  'hobbies',
  'cv_title',
  'driving_license_categories',
  'desired_positions',
  'desired_locations',
  'employment_types',
  'start_availability',
  'salary_min',
  'salary_currency',
  'salary_period',
  'weekend_work',
  'night_work',
  'open_to_relocate_commute',
  'remote_work_only',
  'has_disability',
  'email_job_alerts',
  'gdpr_consent',
  'terms_consent',
  'marketing_consent',
] as const

export type CvHeaderPatchFieldKey = (typeof CV_HEADER_PATCH_FIELD_KEYS)[number]
