import { SupabaseService } from '../supabase/supabase.service';
import { type AwardResponseDto, type AwardUpsertDto, type CertificationResponseDto, type CertificationUpsertDto, type CvAggregateResponseDto, type CvCreateDto, type CvHeaderPatchDto, type CvHeaderResponseDto, type CvListItemResponseDto, type CvPhotoUpsertDto, type EducationResponseDto, type EducationUpsertDto, type ExperienceResponseDto, type ExperienceUpsertDto, type LanguageResponseDto, type LanguageUpsertDto, type LinkResponseDto, type LinkUpsertDto, type PortfolioLinkResponseDto, type PortfolioLinkUpsertDto, type ReferenceResponseDto, type ReferenceUpsertDto, type SkillResponseDto, type SkillUpsertDto, type SoftSkillResponseDto, type SoftSkillUpsertDto, type VolunteeringResponseDto, type VolunteeringUpsertDto } from './cv.dto';
import { CvPdfService } from './cv-pdf.service';
declare const SECTION_TABLES: {
    readonly experience: "cv_experience";
    readonly education: "cv_education";
    readonly skills: "cv_skills";
    readonly soft_skills: "cv_soft_skills";
    readonly languages: "cv_languages";
    readonly certifications: "cv_certifications";
    readonly links: "cv_links";
    readonly volunteering: "cv_volunteering";
    readonly portfolio_links: "cv_portfolio_links";
    readonly awards: "cv_awards";
    readonly references: "cv_references";
};
type SectionKey = keyof typeof SECTION_TABLES;
export declare class CvService {
    private supabase;
    private cvPdf;
    constructor(supabase: SupabaseService, cvPdf: CvPdfService);
    private loadHeaderForShell;
    private findShellRow;
    private findDefaultShellRowForUser;
    private findPersonalRow;
    private findJobRow;
    assertWorkerRole(userId: string): Promise<void>;
    listMyCvs(userId: string): Promise<CvListItemResponseDto[]>;
    assertCvOwned(userId: string, cvId: string): Promise<void>;
    createCv(userId: string, body: CvCreateDto): Promise<CvHeaderResponseDto>;
    deleteCv(userId: string, cvId: string): Promise<void>;
    getOrCreateMyCv(userId: string): Promise<CvHeaderResponseDto>;
    patchMyCv(userId: string, patch: CvHeaderPatchDto): Promise<CvHeaderResponseDto>;
    patchCv(userId: string, cvId: string, patch: CvHeaderPatchDto): Promise<CvHeaderResponseDto>;
    getOwnerAggregateByCvId(cvId: string, ownerUserId: string): Promise<CvAggregateResponseDto | null>;
    getAggregateByCvId(cvId: string, viewerUserId: string | null | undefined): Promise<CvAggregateResponseDto | null>;
    getAggregateByUserId(userId: string, viewerUserId?: string | null): Promise<CvAggregateResponseDto | null>;
    isCvEligibleForEmployerDatabase(cvId: string): Promise<boolean>;
    private sanitizeHeaderForEmployerDatabaseView;
    getEmployerAggregateByCvId(employerUserId: string, cvId: string): Promise<CvAggregateResponseDto | null>;
    private mapExperienceRow;
    private mapEducationRow;
    private mapLanguageRow;
    private mapCertificationRow;
    private mapVolunteeringRow;
    private sanitizeHeaderForPublic;
    private isEmployerViewer;
    private validateHeaderValues;
    private validateEducationBody;
    addExperience(userId: string, cvId: string, body: ExperienceUpsertDto): Promise<ExperienceResponseDto>;
    updateExperience(userId: string, cvId: string, rowId: string, body: ExperienceUpsertDto): Promise<ExperienceResponseDto>;
    addEducation(userId: string, cvId: string, body: EducationUpsertDto): Promise<EducationResponseDto>;
    updateEducation(userId: string, cvId: string, rowId: string, body: EducationUpsertDto): Promise<EducationResponseDto>;
    addSkill(userId: string, cvId: string, body: SkillUpsertDto): Promise<SkillResponseDto>;
    addSoftSkill(userId: string, cvId: string, body: SoftSkillUpsertDto): Promise<SoftSkillResponseDto>;
    addLanguage(userId: string, cvId: string, body: LanguageUpsertDto): Promise<LanguageResponseDto>;
    updateLanguage(userId: string, cvId: string, rowId: string, body: LanguageUpsertDto): Promise<LanguageResponseDto>;
    addCertification(userId: string, cvId: string, body: CertificationUpsertDto): Promise<CertificationResponseDto>;
    updateCertification(userId: string, cvId: string, rowId: string, body: CertificationUpsertDto): Promise<CertificationResponseDto>;
    addLink(userId: string, cvId: string, body: LinkUpsertDto): Promise<LinkResponseDto>;
    updateLink(userId: string, cvId: string, rowId: string, body: LinkUpsertDto): Promise<LinkResponseDto>;
    addVolunteering(userId: string, cvId: string, body: VolunteeringUpsertDto): Promise<VolunteeringResponseDto>;
    updateVolunteering(userId: string, cvId: string, rowId: string, body: VolunteeringUpsertDto): Promise<VolunteeringResponseDto>;
    addPortfolioLink(userId: string, cvId: string, body: PortfolioLinkUpsertDto): Promise<PortfolioLinkResponseDto>;
    updatePortfolioLink(userId: string, cvId: string, rowId: string, body: PortfolioLinkUpsertDto): Promise<PortfolioLinkResponseDto>;
    addAward(userId: string, cvId: string, body: AwardUpsertDto): Promise<AwardResponseDto>;
    updateAward(userId: string, cvId: string, rowId: string, body: AwardUpsertDto): Promise<AwardResponseDto>;
    addReference(userId: string, cvId: string, body: ReferenceUpsertDto): Promise<ReferenceResponseDto>;
    updateReference(userId: string, cvId: string, rowId: string, body: ReferenceUpsertDto): Promise<ReferenceResponseDto>;
    deleteChildRow(userId: string, cvId: string, section: SectionKey, rowId: string): Promise<void>;
    reorderSection(userId: string, cvId: string, section: SectionKey, ids: string[]): Promise<void>;
    uploadPhoto(userId: string, cvId: string, body: CvPhotoUpsertDto): Promise<CvHeaderResponseDto>;
    uploadPhotoFromFile(userId: string, cvId: string, buffer: Buffer, options?: {
        declaredMime?: string;
        filename?: string;
    }): Promise<CvHeaderResponseDto>;
    applyPhotoFromDirectUpload(userId: string, cvId: string, result: {
        publicUrl: string;
        storagePath: string;
        mime: string;
    }): Promise<CvHeaderResponseDto>;
    deletePhoto(userId: string, cvId: string): Promise<CvHeaderResponseDto>;
    generatePdf(userId: string, cvId: string): Promise<{
        filename: string;
        bytes: Buffer;
    }>;
    private listSection;
    private nextSortOrder;
    private insertChildRow;
    private updateChildRow;
    private assertChildOwnedByUser;
}
export {};
