"""Generate SQL seed for public.sk_municipalities from CSV (UTF-8).

Source CSV (snapshot): supabase/seeds/municipalities-slovakia.csv
Original dataset: https://github.com/adammertel/municipalities-slovakia (Wikipedia-derived).
Production deployments may replace with MV SR Register obcí export — see plan.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    csv_path = root / "supabase" / "seeds" / "municipalities-slovakia.csv"
    out_path = root / "supabase" / "migrations" / "20260507120100_sk_municipalities_seed.sql"
    if not csv_path.is_file():
        print(f"Missing CSV: {csv_path}", file=sys.stderr)
        return 1
    rows: list[tuple[str, str, str]] = []
    with csv_path.open(encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            name = (r.get("name") or "").strip()
            kraj = (r.get("region") or "").strip()
            okres = (r.get("district") or "").strip()
            if not name or not kraj or not okres:
                continue
            rows.append((name, kraj, okres))
    seen: set[tuple[str, str]] = set()
    unique_rows: list[tuple[str, str, str]] = []
    for name, kraj, okres in rows:
        key = (name, okres)
        if key in seen:
            continue
        seen.add(key)
        unique_rows.append((name, kraj, okres))
    header = """-- Seed: Slovak municipalities (name, kraj, okres)
-- Generated by supabase/scripts/generate_sk_municipalities_seed.py
-- CSV snapshot: supabase/seeds/municipalities-slovakia.csv
-- Original: https://github.com/adammertel/municipalities-slovakia (Wikipedia). Prefer MV SR Register obcí for authoritative updates.
INSERT INTO public.sk_municipalities (name, kraj, okres) VALUES
"""
    lines: list[str] = []
    for i, (name, kraj, okres) in enumerate(unique_rows):
        suffix = "," if i < len(unique_rows) - 1 else ";"
        lines.append(
            f"  ('{sql_escape(name)}', '{sql_escape(kraj)}', '{sql_escape(okres)}'){suffix}"
        )
    out_path.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(unique_rows)} rows to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
