"""Generate SQL seed for public.sk_education_institutions from CSV (UTF-8).

CSV snapshots:
  supabase/seeds/sk-schools-secondary.csv
  supabase/seeds/sk-schools-universities.csv

Regenerate CSV:
  python supabase/scripts/fetch_cvti_sk_schools.py   # secondary (authoritative)
  python supabase/scripts/build_sk_schools_csv.py  # universities (Wikipedia + curated)
See supabase/seeds/README.md.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def sql_nullable(value: str) -> str:
    v = value.strip()
    if not v:
        return "null"
    return f"'{sql_escape(v)}'"


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    sec_csv = root / "supabase" / "seeds" / "sk-schools-secondary.csv"
    uni_csv = root / "supabase" / "seeds" / "sk-schools-universities.csv"
    out_path = root / "supabase" / "migrations" / "20260623160100_sk_education_institutions_seed.sql"

    if not sec_csv.is_file():
        print("Missing secondary CSV. Run: python supabase/scripts/fetch_cvti_sk_schools.py", file=sys.stderr)
        return 1
    if not uni_csv.is_file():
        print("Missing universities CSV. Run: python supabase/scripts/build_sk_schools_csv.py", file=sys.stderr)
        return 1

    rows: list[tuple[str, str, str, str]] = []
    seen: set[tuple[str, str, str]] = set()

    with sec_csv.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            name = (r.get("name") or "").strip()
            if len(name) < 2:
                continue
            key = (name, "secondary", "SK")
            if key in seen:
                continue
            seen.add(key)
            municipality = (r.get("municipality") or "").strip()
            rows.append((name, "secondary", "SK", municipality))

    with uni_csv.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            name = (r.get("name") or "").strip()
            country = (r.get("country") or "SK").strip().upper()
            if len(name) < 2 or country not in ("SK", "CZ"):
                continue
            key = (name, "university", country)
            if key in seen:
                continue
            seen.add(key)
            municipality = (r.get("municipality") or "").strip()
            rows.append((name, "university", country, municipality))

    header = """-- Seed: Slovak secondary schools + SK/CZ universities
-- Generated by supabase/scripts/generate_sk_schools_seed.py
-- CSV: supabase/seeds/sk-schools-secondary.csv, sk-schools-universities.csv
INSERT INTO public.sk_education_institutions (name, level, country, municipality) VALUES
"""
    lines: list[str] = []
    for i, (name, level, country, municipality) in enumerate(rows):
        suffix = "," if i < len(rows) - 1 else ";"
        lines.append(
            f"  ('{sql_escape(name)}', '{level}', '{country}', {sql_nullable(municipality)}){suffix}"
        )
    out_path.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
