-- Refresh school catalog from CVTI SR Excel registers (~722 secondary schools).
-- Run if 20260623160100 was applied with the old Wikipedia-only seed (~78 secondary).
TRUNCATE public.sk_education_institutions RESTART IDENTITY;

INSERT INTO public.sk_education_institutions (name, level, country, municipality) VALUES
  ('1. súkromné gymnázium v Bratislave', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Arcibiskupské gymnázium biskupa P. Jantauscha, Stredná odborná škola pedagogická bl. Laury a Cirkevná materská škola sv.', 'secondary', 'SK', 'Trnava'),
  ('Bilingválne gymnázium C. S. Lewisa', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Bilingválne gymnázium Milana Hodžu', 'secondary', 'SK', 'Sučany'),
  ('Bilingválne slovensko - španielske gymnázium', 'secondary', 'SK', 'Nové Mesto nad Váhom'),
  ('Cirkevná stredná odborná škola elektrotechnická P. G. Frassatiho', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Cirkevná stredná odborná škola sv.Terézie z Lisieux', 'secondary', 'SK', 'Bánovce nad Bebravou'),
  ('Cirkevné gymnázium Andreja Radlinského ako organizačná zložka Cirkevnej spojenej školy', 'secondary', 'SK', 'Dolný Kubín'),
  ('Cirkevné gymnázium F. Fegyvernekiho s vyučovacím jazykom maďarským - Fegyverneki Ferenc Egyházi Gimnázium - ako organiza', 'secondary', 'SK', 'Šahy'),
  ('Cirkevné gymnázium Marianum s vyučovacím jazykom maďarským - Marianum Egyházi Gimnázium', 'secondary', 'SK', 'Komárno'),
  ('Cirkevné gymnázium sv. Františka z Assisi ako organizačná zložka Cirkevnej spojenej školy', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Cirkevné gymnázium sv. Jána Krstiteľa', 'secondary', 'SK', 'Trebišov'),
  ('Cirkevné gymnázium Štefana Mišíka', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Cirkevné konzervatórium', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Elokované pracovisko ako súčasť Spojenej školy - Praktická škola', 'secondary', 'SK', 'Košice-Západ'),
  ('Elokované pracovisko ako súčasť Školy pre mimoriadne nadané deti a GYMNÁZIUM', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Evanjelická praktická škola internátna ako organizačná zložka Evanjelickej spojenej školy internátnej', 'secondary', 'SK', 'Červenica'),
  ('Evanjelické gymnázium (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Evanjelické gymnázium (Tisovec)', 'secondary', 'SK', 'Tisovec'),
  ('Evanjelické gymnázium ako organizačná zložka Evanjelickej spojenej školy', 'secondary', 'SK', 'Martin'),
  ('Evanjelické gymnázium Jana Amosa Komenského', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Evanjelické gymnázium Juraja Tranovského ako organizačná zložka Evanjelickej spojenej školy', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Evanjelické kolegiálne gymnázium ako organizačná zložka Evanjelickej spojenej školy', 'secondary', 'SK', 'Prešov'),
  ('Evanjelické lýceum', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Gymnázium  sv. Jána Pavla II. ako organizačná zložka Spojenej školy sv. Jána Pavla II.', 'secondary', 'SK', 'Poprad'),
  ('Gymnázium (Bratislava-Dúbravka)', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Gymnázium (Bratislava-Karlova Ves)', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Gymnázium (Bratislava-Rača)', 'secondary', 'SK', 'Bratislava-Rača'),
  ('Gymnázium (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Gymnázium (Bratislava-Staré Mesto)', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Gymnázium (Bytča)', 'secondary', 'SK', 'Bytča'),
  ('Gymnázium (Dubnica nad Váhom)', 'secondary', 'SK', 'Dubnica nad Váhom'),
  ('Gymnázium (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Gymnázium (Košice-Sever)', 'secondary', 'SK', 'Košice-Sever'),
  ('Gymnázium (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Gymnázium (Košice-Vyšné Opátske)', 'secondary', 'SK', 'Košice-Vyšné Opátske'),
  ('Gymnázium (Košice-Západ)', 'secondary', 'SK', 'Košice-Západ'),
  ('Gymnázium (Lipany)', 'secondary', 'SK', 'Lipany'),
  ('Gymnázium (Malacky)', 'secondary', 'SK', 'Malacky'),
  ('Gymnázium (Michalovce)', 'secondary', 'SK', 'Michalovce'),
  ('Gymnázium (Myjava)', 'secondary', 'SK', 'Myjava'),
  ('Gymnázium (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Gymnázium (Nové Zámky)', 'secondary', 'SK', 'Nové Zámky'),
  ('Gymnázium (Partizánske)', 'secondary', 'SK', 'Partizánske'),
  ('Gymnázium (Pezinok)', 'secondary', 'SK', 'Pezinok'),
  ('Gymnázium (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Gymnázium (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Gymnázium (Púchov)', 'secondary', 'SK', 'Púchov'),
  ('Gymnázium (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Gymnázium (Snina)', 'secondary', 'SK', 'Snina'),
  ('Gymnázium (Spišská Nová Ves)', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Gymnázium (Stropkov)', 'secondary', 'SK', 'Stropkov'),
  ('Gymnázium (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Gymnázium (Vráble)', 'secondary', 'SK', 'Vráble'),
  ('Gymnázium (Šurany)', 'secondary', 'SK', 'Šurany'),
  ('Gymnázium (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Gymnázium - Gimnázium', 'secondary', 'SK', 'Kráľovský Chlmec'),
  ('Gymnázium - Gimnázium a Stredná odborná škola - Szakközépiskola', 'secondary', 'SK', 'Fiľakovo'),
  ('Gymnázium - Gimnázium, Gymnázium Jána Amosa Komenského - Comenius Gimnázium a Stredná odborná škola techniky, služieb a', 'secondary', 'SK', 'Štúrovo'),
  ('Gymnázium a Obchodná akadémia', 'secondary', 'SK', 'Trebišov'),
  ('Gymnázium a Stredná odborná škola obchodu a služieb', 'secondary', 'SK', 'Sobrance'),
  ('Gymnázium a Stredná odborná škola techniky a služieb (Gelnica)', 'secondary', 'SK', 'Gelnica'),
  ('Gymnázium a Stredná odborná škola techniky a služieb (Spišská Nová Ves)', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Gymnázium a Stredná odborná škola techniky a služieb - Műszaki és Szolgáltatóipari Szakközépiskola, Mládežnícka 22, Šahy', 'secondary', 'SK', 'Šahy'),
  ('Gymnázium a Stredná športová škola Jozefa Herdu', 'secondary', 'SK', 'Trnava'),
  ('GYMNÁZIUM a Základná škola s vyučovacím jazykom maďarským - Márai Sándor Magyar Tanítási Nyelvű Gimnázium és Alapiskola', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Gymnázium ako organizačná zložka Spojenej školy (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Gymnázium ako organizačná zložka Spojenej školy (Giraltovce)', 'secondary', 'SK', 'Giraltovce'),
  ('Gymnázium ako organizačná zložka Spojenej školy (Liptovský Hrádok)', 'secondary', 'SK', 'Liptovský Hrádok'),
  ('Gymnázium ako organizačná zložka Spojenej školy (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Gymnázium ako organizačná zložka Spojenej školy (Rajec)', 'secondary', 'SK', 'Rajec'),
  ('Gymnázium ako organizačná zložka Spojenej školy (Spišská Stará Ves)', 'secondary', 'SK', 'Spišská Stará Ves'),
  ('Gymnázium ako organizačná zložka Spojenej školy Juraja Turza', 'secondary', 'SK', 'Turzovka'),
  ('Gymnázium ako organizačná zložka Spojenej školy sv. Jozefa', 'secondary', 'SK', 'Nové Mesto nad Váhom'),
  ('Gymnázium ako organizačná zložka Spojenej školy Tarasa Ševčenka s vyučovacím jazykom ukrajinským', 'secondary', 'SK', 'Prešov'),
  ('Gymnázium Alberta Einsteina', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Gymnázium Andreja Kmeťa', 'secondary', 'SK', 'Banská Štiavnica'),
  ('Gymnázium Andreja Sládkoviča', 'secondary', 'SK', 'Banská Bystrica'),
  ('Gymnázium Andreja Sládkoviča a Stredná odborná škola obchodu a služieb', 'secondary', 'SK', 'Krupina'),
  ('Gymnázium Andreja Vrábla', 'secondary', 'SK', 'Levice'),
  ('Gymnázium Angely Merici', 'secondary', 'SK', 'Trnava'),
  ('Gymnázium Antona Bernoláka (Námestovo)', 'secondary', 'SK', 'Námestovo'),
  ('Gymnázium Antona Bernoláka (Senec)', 'secondary', 'SK', 'Senec'),
  ('Gymnázium arm. gen. Ludvíka Svobodu', 'secondary', 'SK', 'Humenné'),
  ('Gymnázium Augusta Horislava Škultétyho, Obchodná akadémia a Stredná odborná škola', 'secondary', 'SK', 'Veľký Krtíš'),
  ('Gymnázium bilingválne', 'secondary', 'SK', 'Žilina'),
  ('Gymnázium bl. biskupa Gojdiča ako organizačná zložka Spojenej školy bl. biskupa Gojdiča', 'secondary', 'SK', 'Prešov'),
  ('Gymnázium bl. Sáry Salkaházi s vyučovacím jazykom maďarským - Boldog Salkaházi Sára Egyházi Gimnázium, ako organizačná z', 'secondary', 'SK', 'Moldava nad Bodvou'),
  ('Gymnázium Boženy Slančíkovej - Timravy a Obchodná akadémia', 'secondary', 'SK', 'Lučenec'),
  ('Gymnázium Cyrila Daxnera', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Gymnázium Dominika Tatarku', 'secondary', 'SK', 'Považská Bystrica'),
  ('Gymnázium duklianskych hrdinov', 'secondary', 'SK', 'Svidník'),
  ('Gymnázium Federica Garcíu Lorcu', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Gymnázium Františka Víťazoslava Sasinka', 'secondary', 'SK', 'Skalica'),
  ('Gymnázium Františka Švantnera', 'secondary', 'SK', 'Nová Baňa'),
  ('Gymnázium Hansa Selyeho s vyučovacím jazykom maďarským - Selye János Gimnázium', 'secondary', 'SK', 'Komárno'),
  ('Gymnázium Imre Madácha s vyučovacím jazykom maďarským - Madách Imre Magyar Tanítási Nyelvű Gimnázium', 'secondary', 'SK', 'Šamorín'),
  ('Gymnázium Ivana Horvátha', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Gymnázium Ivana Kraska - Ivan Krasko Gimnázium a Obchodná akadémia - Kereskedelmi Akadémia', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Gymnázium Ivana Kupca', 'secondary', 'SK', 'Hlohovec'),
  ('Gymnázium Janka Francisciho - Rimavského', 'secondary', 'SK', 'Levoča'),
  ('Gymnázium Janka Jesenského', 'secondary', 'SK', 'Bánovce nad Bebravou'),
  ('Gymnázium Janka Kráľa', 'secondary', 'SK', 'Zlaté Moravce'),
  ('Gymnázium Janka Matúšku', 'secondary', 'SK', 'Galanta'),
  ('Gymnázium Jozefa Cígera Hronského ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Vrútky'),
  ('Gymnázium Jozefa Gregora Tajovského', 'secondary', 'SK', 'Banská Bystrica'),
  ('Gymnázium Jozefa Lettricha', 'secondary', 'SK', 'Martin'),
  ('Gymnázium Jozefa Miloslava Hurbana', 'secondary', 'SK', 'Čadca'),
  ('Gymnázium Juraja Fándlyho', 'secondary', 'SK', 'Šaľa'),
  ('Gymnázium Juraja Szondyho s vyučovacím jazykom maďarským - Szondy György Gimnázium, ako org.zložka Základná škola Lajosa', 'secondary', 'SK', 'Šahy'),
  ('Gymnázium Jána Adama Raymana', 'secondary', 'SK', 'Prešov'),
  ('Gymnázium Jána Baltazára Magina', 'secondary', 'SK', 'Vrbové'),
  ('Gymnázium Jána Chalupku', 'secondary', 'SK', 'Brezno'),
  ('Gymnázium Jána Hollého', 'secondary', 'SK', 'Trnava'),
  ('Gymnázium Jána Papánka', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Gymnázium Karola Štúra', 'secondary', 'SK', 'Modra'),
  ('Gymnázium Kráľovnej pokoja ako organizačná zložka Spojenej školy Kraľovnej pokoja', 'secondary', 'SK', 'Žilina'),
  ('Gymnázium Ladislava Dúbravu', 'secondary', 'SK', 'Dunajská Streda'),
  ('Gymnázium Ladislava Novomeského (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Gymnázium Ladislava Novomeského (Senica)', 'secondary', 'SK', 'Senica'),
  ('Gymnázium Leonarda Stöckela', 'secondary', 'SK', 'Bardejov'),
  ('Gymnázium M. Galandu ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Turčianske Teplice'),
  ('Gymnázium M. R. Štefánika', 'secondary', 'SK', 'Nové Mesto nad Váhom'),
  ('Gymnázium M.R. Štefánika ako organizačná zložka Gymnázia M. R. Štefánika a Základnej školy', 'secondary', 'SK', 'Šamorín'),
  ('Gymnázium Martina Hattalu', 'secondary', 'SK', 'Trstená'),
  ('Gymnázium Martina Kukučína a Stredná odborná škola', 'secondary', 'SK', 'Revúca'),
  ('Gymnázium Matky Alexie', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Gymnázium Michala Miloslava Hodžu', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Gymnázium Mihálya Tompu Reformovanej kresťanskej cirkvi s vyučovacím jazykom maďarským - Tompa Mihály Református Gimnázi', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Gymnázium Mikuláša Kováča', 'secondary', 'SK', 'Banská Bystrica'),
  ('Gymnázium Milana Rastislava Štefánika', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Gymnázium Milana Rúfusa', 'secondary', 'SK', 'Žiar nad Hronom'),
  ('Gymnázium Pavla Horova', 'secondary', 'SK', 'Michalovce'),
  ('Gymnázium Pavla Jozefa Šafárika - Pavol Jozef Šafárik Gimnázium', 'secondary', 'SK', 'Rožňava'),
  ('Gymnázium Pavla Országha Hviezdoslava (Dolný Kubín)', 'secondary', 'SK', 'Dolný Kubín'),
  ('Gymnázium Pavla Országha Hviezdoslava (Kežmarok)', 'secondary', 'SK', 'Kežmarok'),
  ('Gymnázium Petra Pázmáňa s vyučovacím jazykom maďarským - Pázmány Péter Gimnázium', 'secondary', 'SK', 'Nové Zámky'),
  ('Gymnázium Pierra de Coubertina', 'secondary', 'SK', 'Piešťany'),
  ('Gymnázium sv. Andreja', 'secondary', 'SK', 'Ružomberok'),
  ('Gymnázium sv. Cyrila a Metoda ako organizačná zložka Cirkevnej spojenej školy (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Gymnázium sv. Cyrila a Metoda ako organizačná zložka Cirkevnej spojenej školy (Snina)', 'secondary', 'SK', 'Snina'),
  ('Gymnázium sv. Edity Steinovej', 'secondary', 'SK', 'Košice-Dargovských hrdino'),
  ('Gymnázium sv. Františka Assiského', 'secondary', 'SK', 'Levoča'),
  ('Gymnázium sv. Františka Assiského, ako organizačná zložka Spojenej školy sv. Františka Assiského', 'secondary', 'SK', 'Malacky'),
  ('Gymnázium sv. Františka z Assisi', 'secondary', 'SK', 'Žilina'),
  ('Gymnázium sv. Františka z Assisi, ako organizačná zložka Spojenej školy sv. Františka z Assisi', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Gymnázium sv. Jána Bosca ako organizačná zložka Cirkevnej spojenej školy', 'secondary', 'SK', 'Bardejov'),
  ('Gymnázium sv. Jána Zlatoústeho', 'secondary', 'SK', 'Humenné'),
  ('Gymnázium sv. Košických mučeníkov ako organizačná zložka Spojenej školy sv. Košických mučeníkov', 'secondary', 'SK', 'Košice-Sídlisko KVP'),
  ('Gymnázium sv. Mikuláša ako organizačná zložka Katolíckej spojenenej školy sv. Mikuláša', 'secondary', 'SK', 'Prešov'),
  ('Gymnázium sv. Mikuláša ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Stará Ľubovňa'),
  ('Gymnázium sv. Moniky', 'secondary', 'SK', 'Prešov'),
  ('Gymnázium sv. Tomáša Akvinského', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Gymnázium sv. Uršule ako organizačná zložka Spojenej školy sv. Uršule', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Gymnázium sv. Vincenta de Paul ako organizačná zložka Katolíckej spojenej školy sv. Vincenta de Paul', 'secondary', 'SK', 'Levice'),
  ('Gymnázium Svätej Rodiny, ako organizačná zložka Spojenej školy Svätej Rodiny', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Gymnázium Terézie Vansovej', 'secondary', 'SK', 'Stará Ľubovňa'),
  ('Gymnázium Vavrinca Benedikta Nedožerského', 'secondary', 'SK', 'Prievidza'),
  ('Gymnázium Viliama Paulinyho Tótha a Obchodná akadémia', 'secondary', 'SK', 'Martin'),
  ('Gymnázium Vojtecha Mihálika', 'secondary', 'SK', 'Sereď'),
  ('Gymnázium Zoltána Kodálya s vyučovacím jazykom maďarským - Kodály Zoltán Gimnázium', 'secondary', 'SK', 'Galanta'),
  ('Gymnázium Ármina Vámbéryho s vyučovacím jazykom maďarským - Vámbéry Ármin Gimnázium', 'secondary', 'SK', 'Dunajská Streda'),
  ('Gymnázium Ľudovíta Jaroslava Šuleka', 'secondary', 'SK', 'Komárno'),
  ('Gymnázium Ľudovíta Štúra (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Gymnázium Ľudovíta Štúra (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Gymnázium školských bratov, ako organizačná zložka Spojenej školy de La Salle', 'secondary', 'SK', 'Bratislava-Rača'),
  ('Gymnázium Štefana Moysesa a Stredná odborná škola agrotechnická - Agrotechnikai Szakközépiskola', 'secondary', 'SK', 'Moldava nad Bodvou'),
  ('Gymnázium, ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Gymnázium, ako organizačná zložka Spojenej školy sv. Vincenta de Paul', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Gymnázium, Obchodná akadémia a Stredná odborná škola technická', 'secondary', 'SK', 'Detva'),
  ('Gymnázium-Gimnázium a Stredná odborná škola techniky a služieb-Műszaki és Szolgáltatóipari Szakközépiskola', 'secondary', 'SK', 'Veľké Kapušany'),
  ('Hotelová akadémia (Bratislava-Nové Mesto)', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Hotelová akadémia (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Hotelová akadémia (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Hotelová akadémia (Liptovský Mikuláš)', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Hotelová akadémia (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Hotelová akadémia (Spišská Nová Ves)', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Hotelová akadémia (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Hotelová akadémia a Obchodná akadémia', 'secondary', 'SK', 'Brezno'),
  ('Hotelová akadémia Otta Brucknera', 'secondary', 'SK', 'Kežmarok'),
  ('Hotelová akadémia Ľudovíta Wintera', 'secondary', 'SK', 'Piešťany'),
  ('Katolícka spojená škola sv. Františka Assiského', 'secondary', 'SK', 'Banská Štiavnica'),
  ('Katolícke gymnázium Štefana Moysesa', 'secondary', 'SK', 'Banská Bystrica'),
  ('Konzervatórium (Bratislava-Staré Mesto)', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Konzervatórium (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Konzervatórium Jozefa Adamoviča a Konzervatórium Petra Dvorského', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Konzervatórium Jána Levoslava Bellu', 'secondary', 'SK', 'Banská Bystrica'),
  ('Obchodná akadémia (Bratislava-Nové Mesto)', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Obchodná akadémia (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Obchodná akadémia (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Obchodná akadémia (Dolný Kubín)', 'secondary', 'SK', 'Dolný Kubín'),
  ('Obchodná akadémia (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Obchodná akadémia (Košice-Nad jazerom)', 'secondary', 'SK', 'Košice-Nad jazerom'),
  ('Obchodná akadémia (Košice-Sever)', 'secondary', 'SK', 'Košice-Sever'),
  ('Obchodná akadémia (Michalovce)', 'secondary', 'SK', 'Michalovce'),
  ('Obchodná akadémia (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Obchodná akadémia (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Obchodná akadémia (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Obchodná akadémia (Prievidza)', 'secondary', 'SK', 'Prievidza'),
  ('Obchodná akadémia (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Obchodná akadémia (Senica)', 'secondary', 'SK', 'Senica'),
  ('Obchodná akadémia (Sereď)', 'secondary', 'SK', 'Sereď'),
  ('Obchodná akadémia (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Obchodná akadémia (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Obchodná akadémia (Vranov nad Topľou)', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Obchodná akadémia (Šurany)', 'secondary', 'SK', 'Šurany'),
  ('Obchodná akadémia (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Obchodná akadémia - Kereskedelmi Akadémia', 'secondary', 'SK', 'Veľký Meder'),
  ('Obchodná akadémia a Stredná odborná škola obchodu a služieb', 'secondary', 'SK', 'Rožňava'),
  ('Obchodná akadémia a Stredná odborná škola obchodu a služieb, SNP 5, Zlaté Moravce', 'secondary', 'SK', 'Zlaté Moravce'),
  ('Obchodná akadémia ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Svidník'),
  ('Obchodná akadémia Dušana Metoda Janotu', 'secondary', 'SK', 'Čadca'),
  ('Obchodná akadémia Imricha Karvaša', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Obchodná akadémia Mareka Frauwirtha', 'secondary', 'SK', 'Banská Bystrica'),
  ('Obchodná akadémia Milana Hodžu', 'secondary', 'SK', 'Trenčín'),
  ('Obchodná akadémia Petra Zaťka', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Obchodná akadémia sv. Tomáša Akvinského', 'secondary', 'SK', 'Žilina'),
  ('Obchodná akadémia, Ul. Kálmána Kittenbergera 2', 'secondary', 'SK', 'Levice'),
  ('Odborné učilište', 'secondary', 'SK', 'Martin'),
  ('Odborné učilište internátne (Ladce)', 'secondary', 'SK', 'Ladce'),
  ('Odborné učilište internátne (Lučenec)', 'secondary', 'SK', 'Lučenec'),
  ('Odborné učilište internátne (Mojmírovce)', 'secondary', 'SK', 'Mojmírovce'),
  ('Odborné učilište internátne (Nová Ves nad Žitavou)', 'secondary', 'SK', 'Nová Ves nad Žitavou'),
  ('Odborné učilište internátne (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Odborné učilište internátne (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Odborné učilište internátne (Želovce)', 'secondary', 'SK', 'Želovce'),
  ('Odborné učilište internátne - Bentlakásos Speciális Szakiskola ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Okoč'),
  ('Odborné učilište internátne ako organizačná zložka Spojenej školy internátnej', 'secondary', 'SK', 'Tornaľa'),
  ('Odborné učilište internátne Viliama Gaňu', 'secondary', 'SK', 'Banská Bystrica'),
  ('Odborné učilište pri reedukačnom centre', 'secondary', 'SK', 'Veľké Leváre'),
  ('Piaristická spojená škola Františka Hanáka', 'secondary', 'SK', 'Prievidza'),
  ('Piaristické gymnázium Jozefa Braneckého', 'secondary', 'SK', 'Trenčín'),
  ('Piaristické gymnázium sv. Jozefa Kalazanského ako organizačná zložka Piaristickej spojenej školy sv. Jozefa Kalazanského', 'secondary', 'SK', 'Nitra'),
  ('Praktická škola', 'secondary', 'SK', 'Sečovce'),
  ('Praktická škola - Készségfejlesztő ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Kráľovský Chlmec'),
  ('Praktická škola - Készségfejlesztő Iskola ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Sládkovičovo'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Dubnica nad Váhom)', 'secondary', 'SK', 'Dubnica nad Váhom'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Kežmarok)', 'secondary', 'SK', 'Kežmarok'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Komárno)', 'secondary', 'SK', 'Komárno'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Martin)', 'secondary', 'SK', 'Martin'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Myjava)', 'secondary', 'SK', 'Myjava'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Nové Mesto nad Váhom)', 'secondary', 'SK', 'Nové Mesto nad Váhom'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Pavlovce nad Uhom)', 'secondary', 'SK', 'Pavlovce nad Uhom'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Piešťany)', 'secondary', 'SK', 'Piešťany'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Púchov)', 'secondary', 'SK', 'Púchov'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Trenčianska Teplá)', 'secondary', 'SK', 'Trenčianska Teplá'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Vranov nad Topľou)', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Vrbové)', 'secondary', 'SK', 'Vrbové'),
  ('Praktická škola ako organizačná zložka Spojenej školy (Čadca)', 'secondary', 'SK', 'Čadca'),
  ('Praktická škola ako organizačná zložka Spojenej školy internátnej (Bytča)', 'secondary', 'SK', 'Bytča'),
  ('Praktická škola ako organizačná zložka Spojenej školy internátnej (Levice)', 'secondary', 'SK', 'Levice'),
  ('Praktická škola ako organizačná zložka Spojenej školy internátnej (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Praktická škola ako organizačná zložka Spojenej školy internátnej (Prievidza)', 'secondary', 'SK', 'Prievidza'),
  ('Praktická škola ako organizačná zložka Spojenej školy internátnej (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Praktická škola ako súčasť Špeciálnej základnej školy (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Praktická škola ako súčasť Špeciálnej základnej školy (Jelšava)', 'secondary', 'SK', 'Jelšava'),
  ('Praktická škola ako súčasť Špeciálnej základnej školy (Lučenec)', 'secondary', 'SK', 'Lučenec'),
  ('Praktická škola ako súčasť Špeciálnej základnej školy (Rimavská Sobota)', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Praktická škola internátna ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Senica'),
  ('Praktická škola internátna ako organizačná zložka Spojenej školy internátnej (Levoča)', 'secondary', 'SK', 'Levoča'),
  ('Praktická škola internátna ako organizačná zložka Spojenej školy internátnej (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Praktická škola internátna ako organizačná zložka Spojenej školy internátnej (Spišské Vlachy)', 'secondary', 'SK', 'Spišské Vlachy'),
  ('Praktická škola internátna ako organizačná zložka Spojenej školy internátnej (Ždaňa)', 'secondary', 'SK', 'Ždaňa'),
  ('Praktická škola s vyučovacím jazykom maďarským - Készégfejlesztö Iskola ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Dunajská Streda'),
  ('Praktická škola s vyučovacím jazykom maďarským ako súčasť Špeciálnej základnej školy s vyučovacím jazykom maďarským', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Praktická škola sv. Jozefa ako organizačná zložka Spojenej školy sv. Jozefa', 'secondary', 'SK', 'Turzovka'),
  ('Praktická škola sv. Maximiliána Mária Kolbeho ako organizačná zložka Spojenej školy sv.M.M.Kolbeho', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Praktická škola, ako organizačná zložka Spojenej školy (Bratislava-Dúbravka)', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Praktická škola, ako organizačná zložka Spojenej školy (Bratislava-Karlova Ves)', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Praktická škola, ako organizačná zložka Spojenej školy (Malacky)', 'secondary', 'SK', 'Malacky'),
  ('Praktická škola, ako organizačná zložka Spojenej školy (Pezinok)', 'secondary', 'SK', 'Pezinok'),
  ('Praktická škola, ako organizačná zložka Spojenej školy (Senec)', 'secondary', 'SK', 'Senec'),
  ('Premonštrátske gymnázium', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Reedukačné centrum (Hlohovec)', 'secondary', 'SK', 'Hlohovec'),
  ('Reedukačné centrum (Levoča)', 'secondary', 'SK', 'Levoča'),
  ('Reedukačné centrum (Sološnica)', 'secondary', 'SK', 'Sološnica'),
  ('Reedukačné centrum (Tornaľa)', 'secondary', 'SK', 'Tornaľa'),
  ('Spojena škola', 'secondary', 'SK', 'Dunajská Streda'),
  ('Spojená katolícka škola', 'secondary', 'SK', 'Nitra'),
  ('Spojená škola (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Spojená škola (Bardejov)', 'secondary', 'SK', 'Bardejov'),
  ('Spojená škola (Bratislava-Karlova Ves)', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Spojená škola (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Spojená škola (Chminianske Jakubovany)', 'secondary', 'SK', 'Chminianske Jakubovany'),
  ('Spojená škola (Dobšiná)', 'secondary', 'SK', 'Dobšiná'),
  ('Spojená škola (Hlohovec)', 'secondary', 'SK', 'Hlohovec'),
  ('Spojená škola (Holíč)', 'secondary', 'SK', 'Holíč'),
  ('Spojená škola (Ivanka pri Dunaji)', 'secondary', 'SK', 'Ivanka pri Dunaji'),
  ('Spojená škola (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Spojená škola (Košice-Vyšné Opátske)', 'secondary', 'SK', 'Košice-Vyšné Opátske'),
  ('Spojená škola (Lipany)', 'secondary', 'SK', 'Lipany'),
  ('Spojená škola (Medzilaborce)', 'secondary', 'SK', 'Medzilaborce'),
  ('Spojená škola (Moldava nad Bodvou)', 'secondary', 'SK', 'Moldava nad Bodvou'),
  ('Spojená škola (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Spojená škola (Nižná)', 'secondary', 'SK', 'Nižná'),
  ('Spojená škola (Nová Baňa)', 'secondary', 'SK', 'Nová Baňa'),
  ('Spojená škola (Nové Zámky)', 'secondary', 'SK', 'Nové Zámky'),
  ('Spojená škola (Pezinok)', 'secondary', 'SK', 'Pezinok'),
  ('Spojená škola (Poltár)', 'secondary', 'SK', 'Poltár'),
  ('Spojená škola (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Spojená škola (Prievidza)', 'secondary', 'SK', 'Prievidza'),
  ('Spojená škola (Rudňany)', 'secondary', 'SK', 'Rudňany'),
  ('Spojená škola (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Spojená škola (Sabinov)', 'secondary', 'SK', 'Sabinov'),
  ('Spojená škola (Sečovce)', 'secondary', 'SK', 'Sečovce'),
  ('Spojená škola (Spišská Nová Ves)', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Spojená škola (Spišský Štiavnik)', 'secondary', 'SK', 'Spišský Štiavnik'),
  ('Spojená škola (Stará Ľubovňa)', 'secondary', 'SK', 'Stará Ľubovňa'),
  ('Spojená škola (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Spojená škola (Veľké Kapušany)', 'secondary', 'SK', 'Veľké Kapušany'),
  ('Spojená škola (Čaklov)', 'secondary', 'SK', 'Čaklov'),
  ('Spojená škola (Šaľa)', 'secondary', 'SK', 'Šaľa'),
  ('Spojená škola internátna (Bratislava-Karlova Ves)', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Spojená škola internátna (Bratislava-Nové Mesto)', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Spojená škola internátna (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Spojená škola internátna (Kremnica)', 'secondary', 'SK', 'Kremnica'),
  ('Spojená škola internátna (Kysucké Nové Mesto)', 'secondary', 'SK', 'Kysucké Nové Mesto'),
  ('Spojená škola internátna (Levoča)', 'secondary', 'SK', 'Levoča'),
  ('Spojená škola internátna (Liptovský Mikuláš)', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Spojená škola internátna (Medzilaborce)', 'secondary', 'SK', 'Medzilaborce'),
  ('Spojená škola internátna (Michalovce)', 'secondary', 'SK', 'Michalovce'),
  ('Spojená škola internátna (Námestovo)', 'secondary', 'SK', 'Námestovo'),
  ('Spojená škola internátna (Prakovce)', 'secondary', 'SK', 'Prakovce'),
  ('Spojená škola internátna (Rožňava)', 'secondary', 'SK', 'Rožňava'),
  ('Spojená škola internátna (Snina)', 'secondary', 'SK', 'Snina'),
  ('Spojená škola internátna (Stará Ľubovňa)', 'secondary', 'SK', 'Stará Ľubovňa'),
  ('Spojená škola internátna (Svidník)', 'secondary', 'SK', 'Svidník'),
  ('Spojená škola internátna (Trebišov)', 'secondary', 'SK', 'Trebišov'),
  ('Spojená škola internátna (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Spojená škola internátna (Valaská)', 'secondary', 'SK', 'Valaská'),
  ('Spojená škola internátna (Vranov nad Topľou)', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Spojená škola internátna (Šahy)', 'secondary', 'SK', 'Šahy'),
  ('Spojená škola internátna (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Spojená škola Juraja Henischa', 'secondary', 'SK', 'Bardejov'),
  ('Spojená škola Jána Vojtaššáka internátna', 'secondary', 'SK', 'Levoča'),
  ('Spojená škola Pavla Sabadoša internátna', 'secondary', 'SK', 'Prešov'),
  ('Spojená škola Samuela Mikovíniho', 'secondary', 'SK', 'Banská Štiavnica'),
  ('Spojená škola sv. Jána Bosca', 'secondary', 'SK', 'Nová Dubnica'),
  ('Spojená škola sv. Klementa Hofbauera internátna', 'secondary', 'SK', 'Podolínec'),
  ('Stredná odborná škola (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Stredná odborná škola (Handlová)', 'secondary', 'SK', 'Handlová'),
  ('Stredná odborná škola (Hnúšťa)', 'secondary', 'SK', 'Hnúšťa'),
  ('Stredná odborná škola (Kežmarok)', 'secondary', 'SK', 'Kežmarok'),
  ('Stredná odborná škola (Nováky)', 'secondary', 'SK', 'Nováky'),
  ('Stredná odborná škola (Pruské)', 'secondary', 'SK', 'Pruské'),
  ('Stredná odborná škola (Snina)', 'secondary', 'SK', 'Snina'),
  ('Stredná odborná škola (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Stredná odborná škola (Vranov nad Topľou)', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Stredná odborná škola (Žarnovica)', 'secondary', 'SK', 'Žarnovica'),
  ('Stredná odborná škola - Szakközépiskola', 'secondary', 'SK', 'Tornaľa'),
  ('Stredná odborná škola agropotravinárska a technická', 'secondary', 'SK', 'Kežmarok'),
  ('Stredná odborná škola agrotechnická', 'secondary', 'SK', 'Topoľčany'),
  ('Stredná odborná škola automobilová (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná odborná škola automobilová (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná odborná škola automobilová a podnikania', 'secondary', 'SK', 'Senec'),
  ('Stredná odborná škola beauty služieb (Bratislava-Nové Mesto)', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Stredná odborná škola beauty služieb (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná odborná škola chemická', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná odborná škola chemická a Škola umeleckého priemyslu', 'secondary', 'SK', 'Hlohovec'),
  ('Stredná odborná škola chovu koní a služieb - Lótenyésztési és Szolgáltatóipari Szakközépiskola', 'secondary', 'SK', 'Šaľa'),
  ('Stredná odborná škola dopravná (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná odborná škola dopravná (Martin)', 'secondary', 'SK', 'Martin'),
  ('Stredná odborná škola dopravná (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná odborná škola dopravná (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Stredná odborná škola dopravná (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná odborná škola dopravy a služieb (Nové Zámky)', 'secondary', 'SK', 'Nové Zámky'),
  ('Stredná odborná škola dopravy a služieb (Strážske)', 'secondary', 'SK', 'Strážske'),
  ('Stredná odborná škola drevárska (Spišská Nová Ves)', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Stredná odborná škola drevárska (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Stredná odborná škola drevárska (Vranov nad Topľou)', 'secondary', 'SK', 'Vranov nad Topľou'),
  ('Stredná odborná škola drevárska (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Stredná odborná škola drevárska a stavebná', 'secondary', 'SK', 'Krásno nad Kysucou'),
  ('Stredná odborná škola ekonomická', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Stredná odborná škola ekonomická a pedagogická s vyučovacím jazykom maďarským - Közgazdasági és Pedagógiai Szakközépisko', 'secondary', 'SK', 'Senec'),
  ('Stredná odborná škola ekonomiky, hotelierstva a služieb Jána Andraščíka', 'secondary', 'SK', 'Bardejov'),
  ('Stredná odborná škola elektrotechnická (Gbely)', 'secondary', 'SK', 'Gbely'),
  ('Stredná odborná škola elektrotechnická (Liptovský Hrádok)', 'secondary', 'SK', 'Liptovský Hrádok'),
  ('Stredná odborná škola elektrotechnická (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Stredná odborná škola elektrotechnická (Stropkov)', 'secondary', 'SK', 'Stropkov'),
  ('Stredná odborná škola elektrotechnická (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná odborná škola elektrotechnická (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná odborná škola gastronómie a cestovného ruchu', 'secondary', 'SK', 'Nitra'),
  ('Stredná odborná škola gastronómie a hotelových služieb', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Stredná odborná škola gastronómie a služieb (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná odborná škola gastronómie a služieb (Šurany)', 'secondary', 'SK', 'Šurany'),
  ('Stredná odborná škola hotelová', 'secondary', 'SK', 'Vysoké Tatry'),
  ('Stredná odborná škola hotelových služieb a dopravy', 'secondary', 'SK', 'Lučenec'),
  ('Stredná odborná škola hotelových služieb a obchodu (Nové Zámky)', 'secondary', 'SK', 'Nové Zámky'),
  ('Stredná odborná škola hotelových služieb a obchodu (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Stredná odborná škola informačných technológií (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Stredná odborná škola informačných technológií (Bratislava-Rača)', 'secondary', 'SK', 'Bratislava-Rača'),
  ('Stredná odborná škola informačných technológií (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná odborná škola Jána Antonína Baťu', 'secondary', 'SK', 'Partizánske'),
  ('Stredná odborná škola kaderníctva a vizážistiky', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná odborná škola lesnícka (Banská Štiavnica)', 'secondary', 'SK', 'Banská Štiavnica'),
  ('Stredná odborná škola lesnícka (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná odborná škola lesnícka a drevárska Jozefa Dekreta Matejovie', 'secondary', 'SK', 'Liptovský Hrádok'),
  ('Stredná odborná škola letecko - technická', 'secondary', 'SK', 'Trenčín'),
  ('Stredná odborná škola lýceum C. S. Lewisa', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Stredná odborná škola masmediálnych a informačných štúdií', 'secondary', 'SK', 'Bratislava-Rača'),
  ('Stredná odborná škola obchodu a služieb (Dolný Kubín)', 'secondary', 'SK', 'Dolný Kubín'),
  ('Stredná odborná škola obchodu a služieb (Galanta)', 'secondary', 'SK', 'Galanta'),
  ('Stredná odborná škola obchodu a služieb (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Stredná odborná škola obchodu a služieb (Martin)', 'secondary', 'SK', 'Martin'),
  ('Stredná odborná škola obchodu a služieb (Michalovce)', 'secondary', 'SK', 'Michalovce'),
  ('Stredná odborná škola obchodu a služieb (Nové Mesto nad Váhom)', 'secondary', 'SK', 'Nové Mesto nad Váhom'),
  ('Stredná odborná škola obchodu a služieb (Piešťany)', 'secondary', 'SK', 'Piešťany'),
  ('Stredná odborná škola obchodu a služieb (Prievidza)', 'secondary', 'SK', 'Prievidza'),
  ('Stredná odborná škola obchodu a služieb (Púchov)', 'secondary', 'SK', 'Púchov'),
  ('Stredná odborná škola obchodu a služieb (Rimavská Sobota)', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Stredná odborná škola obchodu a služieb (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Stredná odborná škola obchodu a služieb (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná odborná škola obchodu a služieb (Čadca)', 'secondary', 'SK', 'Čadca'),
  ('Stredná odborná škola obchodu a služieb (Žiar nad Hronom)', 'secondary', 'SK', 'Žiar nad Hronom'),
  ('Stredná odborná škola obchodu a služieb - Kereskedelmi és Szolgáltatóipari Szakközépiskola', 'secondary', 'SK', 'Komárno'),
  ('Stredná odborná škola obchodu a služieb a Stredná odborná škola potravinárska', 'secondary', 'SK', 'Topoľčany'),
  ('Stredná odborná škola obchodu a služieb Jána Bocatia', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná odborná škola obchodu a služieb Samuela Jurkoviča', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná odborná škola obchodu, služieb a rozvoja vidieka - Kereskedelmi, Szolgáltatóipari és Vidékfejlesztési Szakközépi', 'secondary', 'SK', 'Kravany nad Dunajom'),
  ('Stredná odborná škola pedagogická (Bratislava-Dúbravka)', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Stredná odborná škola pedagogická (Levice)', 'secondary', 'SK', 'Levice'),
  ('Stredná odborná škola pedagogická (Levoča)', 'secondary', 'SK', 'Levoča'),
  ('Stredná odborná škola pedagogická (Modra)', 'secondary', 'SK', 'Modra'),
  ('Stredná odborná škola pedagogická (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná odborná škola pedagogická (Turčianske Teplice)', 'secondary', 'SK', 'Turčianske Teplice'),
  ('Stredná odborná škola pedagogická - Pedagógiai Szakközépiskola', 'secondary', 'SK', 'Lučenec'),
  ('Stredná odborná škola pedagogická sv. Andreja-Svorada a Benedikta', 'secondary', 'SK', 'Trenčín'),
  ('Stredná odborná škola pedagogická sv. Cyrila a Metoda', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná odborná škola pedagogická sv. Márie Goretti', 'secondary', 'SK', 'Čadca'),
  ('Stredná odborná škola podnikania a služieb (Lipany)', 'secondary', 'SK', 'Lipany'),
  ('Stredná odborná škola podnikania a služieb (Námestovo)', 'secondary', 'SK', 'Námestovo'),
  ('Stredná odborná škola podnikania a služieb (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná odborná škola podnikania v remeslách a službách', 'secondary', 'SK', 'Senica'),
  ('Stredná odborná škola polygrafická', 'secondary', 'SK', 'Bratislava-Rača'),
  ('Stredná odborná škola polytechnická (Dolný Kubín)', 'secondary', 'SK', 'Dolný Kubín'),
  ('Stredná odborná škola polytechnická (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Stredná odborná škola polytechnická (Martin)', 'secondary', 'SK', 'Martin'),
  ('Stredná odborná škola polytechnická (Prievidza)', 'secondary', 'SK', 'Prievidza'),
  ('Stredná odborná škola polytechnická (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Stredná odborná škola polytechnická (Zlaté Moravce)', 'secondary', 'SK', 'Zlaté Moravce'),
  ('Stredná odborná škola polytechnická a služieb arm. gen. L. Svobodu', 'secondary', 'SK', 'Svidník'),
  ('Stredná odborná škola polytechnická Jána Antonína Baťu', 'secondary', 'SK', 'Svit'),
  ('Stredná odborná škola potravinárska', 'secondary', 'SK', 'Nitra'),
  ('Stredná odborná škola poľnohospodárstva a služieb na vidieku (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná odborná škola poľnohospodárstva a služieb na vidieku (Levice)', 'secondary', 'SK', 'Levice'),
  ('Stredná odborná škola poľnohospodárstva a služieb na vidieku (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná odborná škola poľnohospodárstva a služieb na vidieku (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná odborná škola pre žiakov s telesným postihnutím', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Stredná odborná škola pri Reedukačnom centre', 'secondary', 'SK', 'Zlaté Moravce'),
  ('Stredná odborná škola priemyselných technológii', 'secondary', 'SK', 'Košice-Šaca'),
  ('Stredná odborná škola priemyselných technológií', 'secondary', 'SK', 'Púchov'),
  ('Stredná odborná škola regionálneho rozvoja a Stredná odborná škola záhradnícka', 'secondary', 'SK', 'Rakovice'),
  ('Stredná odborná škola remesiel', 'secondary', 'SK', 'Považská Bystrica'),
  ('Stredná odborná škola remesiel a služieb', 'secondary', 'SK', 'Poprad'),
  ('Stredná odborná škola rozvoja vidieka s vyučovacím jazykom maďarským - Vidékfejlesztési Szakközépiskola a Stredná športo', 'secondary', 'SK', 'Dunajská Streda'),
  ('Stredná odborná škola s vyučovacím jazykom maďarským - Szakközépiskola,  ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Rožňava'),
  ('Stredná odborná škola služieb (Levice)', 'secondary', 'SK', 'Levice'),
  ('Stredná odborná škola služieb (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná odborná škola služieb a priemyslu sv. Jozafáta', 'secondary', 'SK', 'Trebišov'),
  ('Stredná odborná škola služieb Majstra Pavla', 'secondary', 'SK', 'Levoča'),
  ('Stredná odborná škola stavebná (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Stredná odborná škola stavebná (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná odborná škola stavebná - Építészeti Szakközépiskola', 'secondary', 'SK', 'Nové Zámky'),
  ('Stredná odborná škola stavebná a Stredná odborná škola agropotravinárska a technická', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Stredná odborná škola strojnícka (Bánovce nad Bebravou)', 'secondary', 'SK', 'Bánovce nad Bebravou'),
  ('Stredná odborná škola strojnícka (Kysucké Nové Mesto)', 'secondary', 'SK', 'Kysucké Nové Mesto'),
  ('Stredná odborná škola strojnícka (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Stredná odborná škola strojnícka (Skalica)', 'secondary', 'SK', 'Skalica'),
  ('Stredná odborná škola sv. Cyrila a Metoda', 'secondary', 'SK', 'Michalovce'),
  ('Stredná odborná škola sv. Jozefa Robotníka', 'secondary', 'SK', 'Žilina'),
  ('Stredná odborná škola technická (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Stredná odborná škola technická (Dubnica nad Váhom)', 'secondary', 'SK', 'Dubnica nad Váhom'),
  ('Stredná odborná škola technická (Hlohovec)', 'secondary', 'SK', 'Hlohovec'),
  ('Stredná odborná škola technická (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Stredná odborná škola technická (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná odborná škola technická (Michalovce)', 'secondary', 'SK', 'Michalovce'),
  ('Stredná odborná škola technická (Námestovo)', 'secondary', 'SK', 'Námestovo'),
  ('Stredná odborná škola technická (Piešťany)', 'secondary', 'SK', 'Piešťany'),
  ('Stredná odborná škola technická (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Stredná odborná škola technická (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná odborná škola technická (Rožňava)', 'secondary', 'SK', 'Rožňava'),
  ('Stredná odborná škola technická (Tlmače)', 'secondary', 'SK', 'Tlmače'),
  ('Stredná odborná škola technická (Vráble)', 'secondary', 'SK', 'Vráble'),
  ('Stredná odborná škola technická (Zlaté Moravce)', 'secondary', 'SK', 'Zlaté Moravce'),
  ('Stredná odborná škola technická (Čadca)', 'secondary', 'SK', 'Čadca'),
  ('Stredná odborná škola technická (Šurany)', 'secondary', 'SK', 'Šurany'),
  ('Stredná odborná škola technická - Múszaki Szakközépiskola (Dunajská Streda)', 'secondary', 'SK', 'Dunajská Streda'),
  ('Stredná odborná škola technická - Múszaki Szakközépiskola (Galanta)', 'secondary', 'SK', 'Galanta'),
  ('Stredná odborná škola technická - Műszaki Szakközépiskola', 'secondary', 'SK', 'Komárno'),
  ('Stredná odborná škola technická a agropotravinárska - Műszaki, Mezőgazdasági és Élelmiszeripari Szakközépiskola', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Stredná odborná škola technická a ekonomická Jozefa Szakkayho - Szakkay József Műszaki és Közgazdasági Szakközépiskola', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná odborná škola techniky a mechanizácie - Műszaki és Gépesítési Szakközépiskola', 'secondary', 'SK', 'Hurbanovo'),
  ('Stredná odborná škola techniky a remesiel - Műszaki Szakok és Mesterségek Szakközépiskola', 'secondary', 'SK', 'Kráľovský Chlmec'),
  ('Stredná odborná škola techniky a služieb (Brezno)', 'secondary', 'SK', 'Brezno'),
  ('Stredná odborná škola techniky a služieb (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Stredná odborná škola techniky a služieb (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Stredná odborná škola techniky a služieb a Stredná priemyselná škola strojnícka a elektrotechnická, Pod amfiteátrom 7, L', 'secondary', 'SK', 'Levice'),
  ('Stredná odborná škola technológií a remesiel', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná odborná škola veterinárna (Košice-Barca)', 'secondary', 'SK', 'Košice-Barca'),
  ('Stredná odborná škola veterinárna (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Stredná odborná škola vinársko - ovocinárska', 'secondary', 'SK', 'Modra'),
  ('Stredná odborná škola železničná', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná priemyselná škola (Dubnica nad Váhom)', 'secondary', 'SK', 'Dubnica nad Váhom'),
  ('Stredná priemyselná škola (Myjava)', 'secondary', 'SK', 'Myjava'),
  ('Stredná priemyselná škola (Nové Mesto nad Váhom)', 'secondary', 'SK', 'Nové Mesto nad Váhom'),
  ('Stredná priemyselná škola (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Stredná priemyselná škola (Snina)', 'secondary', 'SK', 'Snina'),
  ('Stredná priemyselná škola (Stará Turá)', 'secondary', 'SK', 'Stará Turá'),
  ('Stredná priemyselná škola dopravná (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná priemyselná škola dopravná (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná priemyselná škola dopravná (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná priemyselná škola dopravná (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Stredná priemyselná škola elektrotechnická (Bratislava-Dúbravka)', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Stredná priemyselná škola elektrotechnická (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Stredná priemyselná škola elektrotechnická (Bratislava-Staré Mesto)', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Stredná priemyselná škola elektrotechnická (Košice-Sever)', 'secondary', 'SK', 'Košice-Sever'),
  ('Stredná priemyselná škola elektrotechnická (Piešťany)', 'secondary', 'SK', 'Piešťany'),
  ('Stredná priemyselná škola elektrotechnická (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná priemyselná škola informačných technológií a Gymnázium', 'secondary', 'SK', 'Kysucké Nové Mesto'),
  ('Stredná priemyselná škola informačných technológií a umelej inteligencie Skyro', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Stredná priemyselná škola informačných technológií Ignáca Gessaya, Stredná odborná škola lesnícka a Gymnázium', 'secondary', 'SK', 'Tvrdošín'),
  ('Stredná priemyselná škola Jozefa Murgaša', 'secondary', 'SK', 'Banská Bystrica'),
  ('Stredná priemyselná škola stavebná (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Stredná priemyselná škola stavebná (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná priemyselná škola stavebná (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná priemyselná škola stavebná - Építőipari Szakközépiskola', 'secondary', 'SK', 'Hurbanovo'),
  ('Stredná priemyselná škola stavebná a geodetická (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná priemyselná škola stavebná a geodetická (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná priemyselná škola stavebná Dušana Samuela Jurkoviča', 'secondary', 'SK', 'Trnava'),
  ('Stredná priemyselná škola stavebná Emila Belluša', 'secondary', 'SK', 'Trenčín'),
  ('Stredná priemyselná škola stavebná Oskara Winklera - Winkler Oszkár Építőipari Szakközépiskola a Stredná odborná škola t', 'secondary', 'SK', 'Lučenec'),
  ('Stredná priemyselná škola strojnícka (Bratislava-Staré Mesto)', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Stredná priemyselná škola strojnícka (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná priemyselná škola strojnícka (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná priemyselná škola strojnícka a elektrotechnická', 'secondary', 'SK', 'Nitra'),
  ('Stredná priemyselná škola strojnícka a elektrotechnická - Gépipari és Elektrotechnikai Szakközépiskola', 'secondary', 'SK', 'Komárno'),
  ('Stredná priemyselná škola technická (Bardejov)', 'secondary', 'SK', 'Bardejov'),
  ('Stredná priemyselná škola technická (Martin)', 'secondary', 'SK', 'Martin'),
  ('Stredná priemyselná škola technická (Spišská Nová Ves)', 'secondary', 'SK', 'Spišská Nová Ves'),
  ('Stredná priemyselná škola technická (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná priemyselná škola techniky a dizajnu', 'secondary', 'SK', 'Poprad'),
  ('Stredná zdravotnícka škola (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Stredná zdravotnícka škola (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Stredná zdravotnícka škola (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Stredná zdravotnícka škola (Dolný Kubín)', 'secondary', 'SK', 'Dolný Kubín'),
  ('Stredná zdravotnícka škola (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Stredná zdravotnícka škola (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Stredná zdravotnícka škola (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná zdravotnícka škola (Liptovský Mikuláš)', 'secondary', 'SK', 'Liptovský Mikuláš'),
  ('Stredná zdravotnícka škola (Lučenec)', 'secondary', 'SK', 'Lučenec'),
  ('Stredná zdravotnícka škola (Michalovce)', 'secondary', 'SK', 'Michalovce'),
  ('Stredná zdravotnícka škola (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Stredná zdravotnícka škola (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Stredná zdravotnícka škola (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Stredná zdravotnícka škola (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Stredná zdravotnícka škola (Prievidza)', 'secondary', 'SK', 'Prievidza'),
  ('Stredná zdravotnícka škola (Skalica)', 'secondary', 'SK', 'Skalica'),
  ('Stredná zdravotnícka škola (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Stredná zdravotnícka škola (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Stredná zdravotnícka škola (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná zdravotnícka škola - Egészségugyi Középiskola', 'secondary', 'SK', 'Dunajská Streda'),
  ('Stredná zdravotnícka škola - Egészségügyi Középiskola (Nové Zámky)', 'secondary', 'SK', 'Nové Zámky'),
  ('Stredná zdravotnícka škola - Egészségügyi Középiskola (Rožňava)', 'secondary', 'SK', 'Rožňava'),
  ('Stredná zdravotnícka škola Celestíny Šimurkovej v Trenčíne', 'secondary', 'SK', 'Trenčín'),
  ('Stredná zdravotnícka škola M. T. Schererovej', 'secondary', 'SK', 'Ružomberok'),
  ('Stredná zdravotnícka škola milosrdného Samaritána', 'secondary', 'SK', 'Svidník'),
  ('Stredná zdravotnícka škola sv. Alžbety', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Stredná zdravotnícka škola sv. Bazila Veľkého', 'secondary', 'SK', 'Prešov'),
  ('Stredná zdravotnícka škola sv. Františka z Assisi', 'secondary', 'SK', 'Čadca'),
  ('Stredná zdravotnícka škola sv. Vincenta de Paul', 'secondary', 'SK', 'Topoľčany'),
  ('Stredná zdravotnícka škola Štefana Kluberta', 'secondary', 'SK', 'Levoča'),
  ('Stredná športová škola (Banská Bystrica)', 'secondary', 'SK', 'Banská Bystrica'),
  ('Stredná športová škola (Košice-Západ)', 'secondary', 'SK', 'Košice-Západ'),
  ('Stredná športová škola (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Stredná športová škola (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Stredná športová škola (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Stredná športová škola ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Súkromná hotelová akadémia (Banská Štiavnica)', 'secondary', 'SK', 'Banská Štiavnica'),
  ('Súkromná hotelová akadémia (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Súkromná hotelová akadémia - Dufincova', 'secondary', 'SK', 'Michalovce'),
  ('Súkromná hotelová akadémia SD Jednota', 'secondary', 'SK', 'Šamorín'),
  ('Súkromná obchodná akadémia (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromná obchodná akadémia (Považská Bystrica)', 'secondary', 'SK', 'Považská Bystrica'),
  ('Súkromná obchodná akadémia (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Súkromná obchodná akadémia DSA', 'secondary', 'SK', 'Žiar nad Hronom'),
  ('Súkromná obchodná akadémia Profi - Kamo', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Súkromná praktická škola (Košice-Myslava)', 'secondary', 'SK', 'Košice-Myslava'),
  ('Súkromná praktická škola (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Súkromná praktická škola ako organizačná zložka Súkromnej spojenej školy (Detva)', 'secondary', 'SK', 'Detva'),
  ('Súkromná praktická škola ako organizačná zložka Súkromnej spojenej školy (Klokočov)', 'secondary', 'SK', 'Klokočov'),
  ('Súkromná praktická škola ako organizačná zložka Súkromnej spojenej školy (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Súkromná SOŠ automobilová Duálna akadémia', 'secondary', 'SK', 'Bratislava-Devínska Nová'),
  ('Súkromná spojená škola (Kolárovo)', 'secondary', 'SK', 'Kolárovo'),
  ('Súkromná spojená škola (Martin)', 'secondary', 'SK', 'Martin'),
  ('Súkromná spojená škola (Štúrovo)', 'secondary', 'SK', 'Štúrovo'),
  ('Súkromná Spojená škola EDUCO', 'secondary', 'SK', 'Námestovo'),
  ('Súkromná spojená škola EDURAM', 'secondary', 'SK', 'Krompachy'),
  ('Súkromná spojená škola Železiarne Podbrezová', 'secondary', 'SK', 'Podbrezová'),
  ('Súkromná spojená škola, Biela voda', 'secondary', 'SK', 'Kežmarok'),
  ('Súkromná stredná odborná  škola ochrany osôb a majetku', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromná stredná odborná škola  Magán Szakkozépiskola', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Súkromná stredná odborná škola (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Súkromná stredná odborná škola (Bytča)', 'secondary', 'SK', 'Bytča'),
  ('Súkromná stredná odborná škola (Giraltovce)', 'secondary', 'SK', 'Giraltovce'),
  ('Súkromná stredná odborná škola (Hliník nad Hronom)', 'secondary', 'SK', 'Hliník nad Hronom'),
  ('Súkromná stredná odborná škola (Košice-Nad jazerom)', 'secondary', 'SK', 'Košice-Nad jazerom'),
  ('Súkromná stredná odborná škola (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Súkromná stredná odborná škola (Revúca)', 'secondary', 'SK', 'Revúca'),
  ('Súkromná stredná odborná škola (Trebišov)', 'secondary', 'SK', 'Trebišov'),
  ('Súkromná stredná odborná škola (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Súkromná stredná odborná škola (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Súkromná stredná odborná škola - Gastroškola', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Súkromná stredná odborná škola - Magán Szakközépiskola', 'secondary', 'SK', 'Sládkovičovo'),
  ('Súkromná stredná odborná škola ADVENTIM - Magán Szakközépiskola ADVENTIM', 'secondary', 'SK', 'Dunajská Streda'),
  ('Súkromná stredná odborná škola ANIMUS', 'secondary', 'SK', 'Nitra'),
  ('Súkromná stredná odborná škola DSA (Trebišov)', 'secondary', 'SK', 'Trebišov'),
  ('Súkromná stredná odborná škola DSA (Trnava)', 'secondary', 'SK', 'Trnava'),
  ('Súkromná stredná odborná škola ekonomicko-technická', 'secondary', 'SK', 'Košice-Dargovských hrdino'),
  ('Súkromná stredná odborná škola ekonomická KOŠICKÁ AKADÉMIA', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Súkromná stredná odborná škola ELBA', 'secondary', 'SK', 'Prešov'),
  ('Súkromná stredná odborná škola HOST', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Súkromná stredná odborná škola hotelierstva a gastronómie Mladosť', 'secondary', 'SK', 'Prešov'),
  ('Súkromná stredná odborná škola Johannes Senio Service', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromná stredná odborná škola Nová cesta Magán Szakközépiskola Új út', 'secondary', 'SK', 'Malčice'),
  ('Súkromná stredná odborná škola obchodu a služieb', 'secondary', 'SK', 'Očová'),
  ('Súkromná stredná odborná škola obchodu a služieb s vyučovacím jazykom maďarským - Magán Kereskedelmi és Szolgáltatóipari', 'secondary', 'SK', 'Bátorove Kosihy'),
  ('Súkromná stredná odborná škola obchodu a služieb, s vyučovacím jazykom maďarským - Magán Kereskedelmi és Szolgáltatóipar', 'secondary', 'SK', 'Mostová'),
  ('Súkromná stredná odborná škola PAMIKO', 'secondary', 'SK', 'Košice-Juh'),
  ('Súkromná stredná odborná škola pedagogická (Bratislava-Podunajské Bis)', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Súkromná stredná odborná škola pedagogická (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Súkromná stredná odborná škola pedagogická a sociálna (Bratislava-Karlova Ves)', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Súkromná stredná odborná škola pedagogická a sociálna (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Súkromná stredná odborná škola pedagogická EBG (Brezno)', 'secondary', 'SK', 'Brezno'),
  ('Súkromná stredná odborná škola pedagogická EBG (Humenné)', 'secondary', 'SK', 'Humenné'),
  ('Súkromná stredná odborná škola podnikania (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Súkromná stredná odborná škola podnikania (Senica)', 'secondary', 'SK', 'Senica'),
  ('Súkromná stredná odborná škola podnikania (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Súkromná stredná odborná škola polytechnická DSA', 'secondary', 'SK', 'Nitra'),
  ('Súkromná stredná odborná škola Pro scholaris', 'secondary', 'SK', 'Žilina'),
  ('Súkromná stredná odborná škola s vyučovacím jazykom maďarským - Magyar Tannyelvü Magán Szakközépiskola', 'secondary', 'SK', 'Dunajská Streda'),
  ('Súkromná stredná odborná škola SD Jednota', 'secondary', 'SK', 'Šamorín'),
  ('Súkromná stredná odborná škola služieb (Bardejov)', 'secondary', 'SK', 'Bardejov'),
  ('Súkromná stredná odborná škola služieb (Poprad)', 'secondary', 'SK', 'Poprad'),
  ('Súkromná stredná odborná škola technická', 'secondary', 'SK', 'Žiar nad Hronom'),
  ('Súkromná stredná odborná škola veterinárna', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Súkromná stredná odborná škola VIA HUMANA', 'secondary', 'SK', 'Skalica'),
  ('Súkromná stredná športová škola (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromná stredná športová škola (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Súkromná stredná športová škola (Trenčianske Teplice)', 'secondary', 'SK', 'Trenčianske Teplice'),
  ('Súkromná stredná športová škola (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Súkromná stredná športová škola EISB', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Súkromná stredná športová škola ELBA', 'secondary', 'SK', 'Prešov'),
  ('Súkromná stredná športová škola GAUDEAMUS', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Súkromná škola umeleckého priemyslu (Hodruša-Hámre)', 'secondary', 'SK', 'Hodruša-Hámre'),
  ('Súkromná škola umeleckého priemyslu (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Súkromná škola umeleckého priemyslu (Topoľčany)', 'secondary', 'SK', 'Topoľčany'),
  ('Súkromná škola umeleckého priemyslu (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Súkromná škola umeleckého priemyslu (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Súkromná škola umeleckého priemyslu a vizuálneho umenia', 'secondary', 'SK', 'Zvolen'),
  ('Súkromná škola umeleckého priemyslu animovanej tvorby', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromná škola umeleckého priemyslu Bohumila Baču', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Súkromná škola umeleckého priemyslu filmová', 'secondary', 'SK', 'Košice-Západ'),
  ('Súkromné bilingválne gymnázium (Galanta)', 'secondary', 'SK', 'Galanta'),
  ('Súkromné bilingválne gymnázium (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Súkromné bilingválne gymnázium BESST', 'secondary', 'SK', 'Trnava'),
  ('Súkromné bilingválne gymnázium Co.Bra.', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Súkromné bulharské gymnázium Christa Boteva', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromné gymnázium (Bratislava-Nové Mesto)', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Súkromné gymnázium (Bratislava-Petržalka)', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromné gymnázium (Bratislava-Vrakuňa)', 'secondary', 'SK', 'Bratislava-Vrakuňa'),
  ('Súkromné gymnázium (Košice-Nad jazerom)', 'secondary', 'SK', 'Košice-Nad jazerom'),
  ('Súkromné gymnázium (Košice-Západ)', 'secondary', 'SK', 'Košice-Západ'),
  ('Súkromné gymnázium (Kremnica)', 'secondary', 'SK', 'Kremnica'),
  ('Súkromné gymnázium (Lučenec)', 'secondary', 'SK', 'Lučenec'),
  ('Súkromné gymnázium (Žilina)', 'secondary', 'SK', 'Žilina'),
  ('Súkromné gymnázium ako organizačná zložka Spojenej školy', 'secondary', 'SK', 'Poprad'),
  ('Súkromné gymnázium ako organizačná zložka Súkromnej spojenej školy', 'secondary', 'SK', 'Košice-Košická Nová Ves'),
  ('Súkromné gymnázium ako organizačná zložka Súkromnej spojenej školy European English School', 'secondary', 'SK', 'Prešov'),
  ('Súkromné gymnázium Banskobystrické', 'secondary', 'SK', 'Banská Bystrica'),
  ('Súkromné gymnázium British International School Bratislava, ako organizačná zložka Súkromnej spojenej školy British Inte', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Súkromné gymnázium Cambridge International School,  ako organizačná zložka Súkromnej spojenej školy Cambridge Internatio', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Súkromné gymnázium DSA', 'secondary', 'SK', 'Bardejov'),
  ('Súkromné Gymnázium DSA', 'secondary', 'SK', 'Sabinov'),
  ('Súkromné gymnázium ESPRIT', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Súkromné gymnázium FELIX', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Súkromné Gymnázium francúzsko-slovenské ako organizačná zložka Súkromnej spojenej školy francúzsko-slovenskej', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromné gymnázium FUTURUM (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Súkromné gymnázium FUTURUM (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Súkromné gymnázium GALILEO SCHOOL', 'secondary', 'SK', 'Bratislava-Podunajské Bis'),
  ('Súkromné gymnázium MERCURY', 'secondary', 'SK', 'Bratislava-Petržalka'),
  ('Súkromné gymnázium nemecko-slovenské', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Súkromné gymnázium pre žiakov so všeobecným intelektovým nadaním CENADA', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Súkromné gymnázium Quality Schools International ako organizačná zložka Súkromnej spojenej školy Quality Schools Interna', 'secondary', 'SK', 'Šamorín'),
  ('Súkromné gymnázium s vyučovacím jazykom maďarským - Magyar Tanítási Nyelvu Magángimnázium', 'secondary', 'SK', 'Dunajská Streda'),
  ('Súkromné gymnázium, ako organizačná zložka Súkromnej spojenej školy Kings Schools International', 'secondary', 'SK', 'Bratislava-Nové Mesto'),
  ('Súkromné hudobné a dramatické konzervatórium (Košice-Juh)', 'secondary', 'SK', 'Košice-Juh'),
  ('Súkromné hudobné a dramatické konzervatórium (Rimavská Sobota)', 'secondary', 'SK', 'Rimavská Sobota'),
  ('Súkromné konzervatórium (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Súkromné konzervatórium (Nitra)', 'secondary', 'SK', 'Nitra'),
  ('Súkromné konzervatórium (Zvolen)', 'secondary', 'SK', 'Zvolen'),
  ('Súkromné konzervatórium ALKANA', 'secondary', 'SK', 'Bratislava-Dúbravka'),
  ('Súkromné konzervatórium Dezidera Kardoša', 'secondary', 'SK', 'Topoľčany'),
  ('Súkromné konzervatórium Prešov', 'secondary', 'SK', 'Prešov'),
  ('Súkromné odborné učilište', 'secondary', 'SK', 'Stropkov'),
  ('Súkromné odborné učilište ELBA', 'secondary', 'SK', 'Svinia'),
  ('Súkromné tanečné konzervatórium', 'secondary', 'SK', 'Liptovský Hrádok'),
  ('Súkromné tanečné konzervatórium Dušana Nebylu', 'secondary', 'SK', 'Trnava'),
  ('Tanečné konzervatórium Evy Jaczovej', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Základná škola a GYMNÁZIUM s vyučovacím jazykom maďarským - Magyar Tannyelvű Alapiskola és Gimnázium', 'secondary', 'SK', 'Bratislava-Staré Mesto'),
  ('Škola umeleckého priemyslu (Bratislava-Ružinov)', 'secondary', 'SK', 'Bratislava-Ružinov'),
  ('Škola umeleckého priemyslu (Kežmarok)', 'secondary', 'SK', 'Kežmarok'),
  ('Škola umeleckého priemyslu (Košice-Staré Mesto)', 'secondary', 'SK', 'Košice-Staré Mesto'),
  ('Škola umeleckého priemyslu (Prešov)', 'secondary', 'SK', 'Prešov'),
  ('Škola umeleckého priemyslu (Ružomberok)', 'secondary', 'SK', 'Ružomberok'),
  ('Škola umeleckého priemyslu (Svidník)', 'secondary', 'SK', 'Svidník'),
  ('Škola umeleckého priemyslu (Trenčín)', 'secondary', 'SK', 'Trenčín'),
  ('Škola umeleckého priemyslu Josefa Vydru', 'secondary', 'SK', 'Bratislava-Karlova Ves'),
  ('Škola umeleckého priemyslu Ladislava Bielika', 'secondary', 'SK', 'Levice'),
  ('AMBIS vysoká škola', 'university', 'SK', null),
  ('Academia Rerum Civilium – Vysoká škola politických a společenských věd', 'university', 'CZ', null),
  ('Akademie Huspol', 'university', 'CZ', null),
  ('Akademie múzických umění v Praze', 'university', 'CZ', 'Praha'),
  ('Akademie výtvarných umění v Praze', 'university', 'CZ', 'Praha'),
  ('Akadémia Policajného zboru v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Akadémia médií, odborná vysoká škola mediálnej a marketingovej komunikácie v Bratislave', 'university', 'SK', 'Bratislave'),
  ('Akadémia ozbrojených síl generála M. R. Štefánika', 'university', 'SK', 'Liptovský Mikuláš'),
  ('Akadémia ozbrojených síl generála Milana Rastislava Štefánika', 'university', 'SK', null),
  ('Akadémia umení v Banskej Bystrici', 'university', 'SK', 'Banskej Bystrici'),
  ('Akreditační komise', 'university', 'CZ', null),
  ('Ambis Univerzita', 'university', 'CZ', null),
  ('Archip', 'university', 'CZ', null),
  ('B.I.B.S.', 'university', 'CZ', null),
  ('Bratislavská medzinárodná škola liberálnych štúdií', 'university', 'SK', null),
  ('CEVRO Univerzita', 'university', 'CZ', null),
  ('Collegium Humanum', 'university', 'CZ', null),
  ('Collegium Humanum – Varšavská univerzita manažmentu', 'university', 'SK', null),
  ('Ekonomická univerzita v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Filmová akademie Miroslava Ondříčka v Písku', 'university', 'CZ', 'Písku'),
  ('International ART CAMPUS Prague', 'university', 'CZ', null),
  ('Janáčkova akademie múzických umění', 'university', 'CZ', null),
  ('Jihočeská univerzita v Českých Budějovicích', 'university', 'CZ', 'České Budějovice'),
  ('Katolícka univerzita v Ružomberku', 'university', 'SK', 'Ružomberok'),
  ('Masarykova univerzita', 'university', 'CZ', 'Brno'),
  ('Mendelova univerzita v Brně', 'university', 'CZ', 'Brno'),
  ('Metropolitní univerzita Praha', 'university', 'CZ', null),
  ('Miss Academia', 'university', 'CZ', null),
  ('Moravská vysoká škola Olomouc', 'university', 'CZ', null),
  ('Národní akreditační úřad pro terciární vzdělávání', 'university', 'CZ', null),
  ('Ostravská univerzita', 'university', 'CZ', null),
  ('Paneurópska vysoká škola', 'university', 'SK', null),
  ('Panevropská univerzita', 'university', 'CZ', null),
  ('Pražská vysoká škola psychosociálních studií', 'university', 'CZ', null),
  ('Prešovská univerzita v Prešove', 'university', 'SK', 'Prešove'),
  ('Rada vysokých škol', 'university', 'CZ', null),
  ('Reforma vysokých škol v Česku', 'university', 'CZ', 'Česku'),
  ('Seznam fakult podle vysokých škol v Česku', 'university', 'CZ', 'Česku'),
  ('Seznam fakult vysokých škol v Česku podle oborů', 'university', 'CZ', 'Česku podle oborů'),
  ('Seznam vysokých škol v Česku', 'university', 'CZ', 'Česku'),
  ('Seznam československých stranických a politických škol', 'university', 'CZ', null),
  ('Slezská univerzita v Opavě', 'university', 'CZ', 'Opava'),
  ('Slovenská poľnohospodárska univerzita v Nitre', 'university', 'SK', 'Nitra'),
  ('Slovenská technická univerzita v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Slovenská zdravotnícka univerzita v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Soukromá vysoká škola ekonomická Znojmo', 'university', 'CZ', null),
  ('Soukromá vysoká škola ekonomických studií', 'university', 'CZ', null),
  ('Stredoeurópska vysoká škola v Skalici', 'university', 'SK', 'Skalici'),
  ('Studentské unie v Česku', 'university', 'CZ', 'Česku'),
  ('Středočeský vysokoškolský institut', 'university', 'CZ', null),
  ('Technická univerzita v Košiciach', 'university', 'SK', 'Košice'),
  ('Technická univerzita v Liberci', 'university', 'CZ', 'Liberec'),
  ('Technická univerzita vo Zvolene', 'university', 'SK', 'Zvolen'),
  ('Trenčianska univerzita Alexandra Dubčeka v Trenčíne', 'university', 'SK', 'Trenčíne'),
  ('Trnavská univerzita v Trnave', 'university', 'SK', 'Trnave'),
  ('Ukrajinský vyšší pedagogický institut', 'university', 'CZ', null),
  ('Unicorn University', 'university', 'CZ', null),
  ('University College Prague', 'university', 'CZ', null),
  ('University of New York in Prague', 'university', 'CZ', null),
  ('Univerzita Alexandra Dubčeka v Trenčíne', 'university', 'SK', 'Trenčín'),
  ('Univerzita Hradec Králové', 'university', 'CZ', 'Hradec Králové'),
  ('Univerzita J. Selyeho', 'university', 'SK', null),
  ('Univerzita J. Selyeho v Komárne', 'university', 'SK', 'Komárno'),
  ('Univerzita Jana Amose Komenského Praha', 'university', 'CZ', null),
  ('Univerzita Jana Evangelisty Purkyně v Ústí nad Labem', 'university', 'CZ', 'Ústí nad Labem'),
  ('Univerzita Karlova', 'university', 'CZ', 'Praha'),
  ('Univerzita Komenského v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Univerzita Konštantína Filozofa v Nitre', 'university', 'SK', 'Nitra'),
  ('Univerzita Mateja Bela v Banskej Bystrici', 'university', 'SK', 'Banská Bystrica'),
  ('Univerzita Ostrava', 'university', 'CZ', 'Ostrava'),
  ('Univerzita Palackého v Olomouci', 'university', 'CZ', 'Olomouc'),
  ('Univerzita Pardubice', 'university', 'CZ', 'Pardubice'),
  ('Univerzita Pavla Jozefa Šafárika v Košiciach', 'university', 'SK', 'Košice'),
  ('Univerzita Tomáše Bati ve Zlíně', 'university', 'CZ', 'Zlín'),
  ('Univerzita prešovská', 'university', 'SK', 'Prešov'),
  ('Univerzita sv. Alžbety v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Univerzita sv. Cyrila a Metoda v Trnave', 'university', 'SK', 'Trnava'),
  ('Univerzita třetího věku', 'university', 'CZ', null),
  ('Univerzita v Trnave', 'university', 'SK', 'Trnava'),
  ('Univerzita v Žiline', 'university', 'SK', 'Žilina'),
  ('Univerzita veterinárskeho lekárstva a farmácie v Košiciach', 'university', 'SK', 'Košice'),
  ('Uzavření českých vysokých škol 17. listopadu 1939', 'university', 'CZ', null),
  ('Veterinární univerzita Brno', 'university', 'CZ', null),
  ('Vojenská katedra', 'university', 'CZ', null),
  ('Vysokoškolské katolické hnutí', 'university', 'CZ', null),
  ('Vysoká škola DTI', 'university', 'SK', null),
  ('Vysoká škola Danubius', 'university', 'SK', 'Bratislava'),
  ('Vysoká škola Goethe Uni Bratislava', 'university', 'SK', null),
  ('Vysoká škola Jagiellonská', 'university', 'CZ', null),
  ('Vysoká škola Karla Engliše', 'university', 'CZ', null),
  ('Vysoká škola Karlovy Vary', 'university', 'CZ', null),
  ('Vysoká škola NEWTON', 'university', 'CZ', null),
  ('Vysoká škola Sting', 'university', 'CZ', null),
  ('Vysoká škola aplikované psychologie', 'university', 'CZ', null),
  ('Vysoká škola aplikovaného práva', 'university', 'CZ', null),
  ('Vysoká škola bezpečnostného manažérstva v Košiciach', 'university', 'SK', 'Košice'),
  ('Vysoká škola báňská – Technická univerzita Ostrava', 'university', 'CZ', null),
  ('Vysoká škola chemicko-technologická v Praze', 'university', 'CZ', 'Praha'),
  ('Vysoká škola ekonomická v Praze', 'university', 'CZ', 'Praha'),
  ('Vysoká škola ekonomie a managementu', 'university', 'CZ', null),
  ('Vysoká škola ekonómie a manažmentu verejnej správy v Bratislave', 'university', 'SK', 'Bratislave'),
  ('Vysoká škola evropských a regionálních studií', 'university', 'CZ', null),
  ('Vysoká škola finanční a správní', 'university', 'CZ', null),
  ('Vysoká škola logistiky', 'university', 'CZ', null),
  ('Vysoká škola manažmentu v Trenčíne', 'university', 'SK', 'Trenčíne'),
  ('Vysoká škola mezinárodních a veřejných vztahů Praha', 'university', 'CZ', null),
  ('Vysoká škola múzických umení v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Vysoká škola obchodní a hotelová', 'university', 'CZ', null),
  ('Vysoká škola polytechnická Jihlava', 'university', 'CZ', null),
  ('Vysoká škola technická a ekonomická v Prešove', 'university', 'SK', 'Prešove'),
  ('Vysoká škola technická a ekonomická v Českých Budějovicích', 'university', 'CZ', 'Českých Budějovicích'),
  ('Vysoká škola tělesné výchovy a sportu Palestra', 'university', 'CZ', null),
  ('Vysoká škola uměleckoprůmyslová v Praze', 'university', 'CZ', 'Praze'),
  ('Vysoká škola výtvarných umení v Bratislave', 'university', 'SK', 'Bratislava'),
  ('Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave', 'university', 'SK', 'Bratislave'),
  ('Vysoké učení technické v Brně', 'university', 'CZ', 'Brno'),
  ('Západomoravská vysoká škola Třebíč', 'university', 'CZ', null),
  ('Západočeská univerzita v Plzni', 'university', 'CZ', 'Plzeň'),
  ('Česká asociace doktorandek a doktorandů', 'university', 'CZ', null),
  ('Česká konference rektorů', 'university', 'CZ', null),
  ('Česká zemědělská univerzita v Praze', 'university', 'CZ', 'Praha'),
  ('České vysoké učení technické v Praze', 'university', 'CZ', 'Praha'),
  ('Škoda Auto Vysoká škola', 'university', 'CZ', null),
  ('Žilinská univerzita v Žiline', 'university', 'SK', 'Žiline');
